package com.tradinganalytics.research.legacy;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.NullNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.tradinganalytics.research.swing.SwingEngine;
import java.io.IOException;
import java.io.InputStream;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

import static com.tradinganalytics.research.legacy.LegacyResearchSupport.*;

/** Authoritative evaluator backing the legacy strategy-research/2 API. */
final class LegacyResearchV2Evaluator {
    private LegacyResearchV2Evaluator() {}

    static ObjectNode evaluate(JsonNode options) {
        object(options, "options");
        JsonNode experiment = options.get("experiment"), definition = options.get("definition"), candidateSet = options.get("candidateSet"), precommit = options.get("precommit"), dataManifest = options.get("dataManifest");
        LegacyResearchV2.validatePrecommit(precommit); LegacyResearchV2.validateDefinitionV2(definition, precommit); LegacyResearchV2.validateExperimentV2(experiment, definition); LegacyResearchV2.validateCandidateSetV2(candidateSet, experiment);
        String phase = text(experiment.get("evidence_phase")); if ("SEALED_CONFIRMATION".equals(phase)) throw new IllegalArgumentException("SEALED_CONFIRMATION cannot be minted by the local v2 path; import an externally verified attestation");
        ObjectNode chronologyOptions = JSON.objectNode().put("requireFolds", "WALK_FORWARD_OOS".equals(phase)); LegacyResearchV2.validateEvaluationChronology(experiment, chronologyOptions);
        String adapter = optionText(options, "adapter", "swing-engine/1"); if (!LegacyResearchV2.EXECUTOR_ADAPTERS.contains(adapter)) throw new IllegalArgumentException("executor adapter capability unavailable: " + adapter);
        JsonNode grid = experiment.has("grid") ? experiment.get("grid") : JSON.objectNode(); if (present(experiment.get("parameter_topology")) || (grid.isObject() && !grid.isEmpty())) LegacyResearchV2.validateParameterTopology(experiment.has("parameter_topology") ? experiment.get("parameter_topology") : JSON.objectNode(), grid);
        if (candidateSet.has("parameter_topology_sha256") && !text(candidateSet.get("parameter_topology_sha256")).equals(LegacyResearchV2.hash(experiment.has("parameter_topology") ? experiment.get("parameter_topology") : JSON.objectNode()))) throw new IllegalArgumentException("candidate set parameter topology hash mismatch");
        List<String> requiredAssets = new ArrayList<>(); for (JsonNode value : rows(experiment.get("required_assets"))) requiredAssets.add(assetName(value));
        ObjectNode manifestOptions = JSON.objectNode().put("phase", phase); manifestOptions.set("requiredAssets", strings(requiredAssets)); LegacyResearchV2.validateDataManifest(dataManifest, manifestOptions);

        JsonNode featureStoreInput = options.get("featureStore"); ObjectNode store;
        if (featureStoreInput != null && featureStoreInput.isTextual()) { try { store = SwingEngine.readFeatureStoreArtifact(Path.of(featureStoreInput.textValue())); } catch (IOException error) { throw new IllegalArgumentException(error.getMessage(), error); } }
        else store = objectCopy(featureStoreInput, "featureStore");
        if (!"swing-feature-store/1".equals(text(store.get("schema"))) || !SwingEngine.verifyFeatureStoreHash(store)) throw new IllegalArgumentException("feature store content hash verification failed");
        if (!text(store.get("features_sha256")).matches("^[a-f0-9]{64}$")) throw new IllegalArgumentException("feature store hash is required");
        if (!text(dataManifest.path("feature_store").get("sha256")).equals(text(store.get("features_sha256")))) throw new IllegalArgumentException("data manifest feature-store hash mismatch");
        if (!store.path("point_in_time_safe").asBoolean(false) && !"DEVELOPMENT".equals(phase)) throw new IllegalArgumentException("feature store is not point-in-time safe for " + phase);
        ArrayNode decoded = SwingEngine.decodeFeatureStore(store); if (dataManifest.path("feature_store").has("row_count") && jsNumber(dataManifest.path("feature_store").get("row_count")) != decoded.size()) throw new IllegalArgumentException("data manifest feature-store row count mismatch");
        validateManifestIdentities(decoded, dataManifest);

        JsonNode chronology = experiment.get("evaluation_chronology"); for (JsonNode seed : rows(chronology.get("seeds"))) if (!Double.isFinite(jsNumber(seed))) throw new IllegalArgumentException("evaluation chronology seeds must be finite"); int seed = (int) jsNumber(chronology.path("seeds").get(0)); JsonNode executorConfig = options.has("executorConfig") ? options.get("executorConfig") : JSON.objectNode();
        ObjectNode executor = executor(adapter, executorConfig, chronology, store, dataManifest, options); String executorIdentity = LegacyResearchV2.hash(executor);
        if ("PROSPECTIVE_LIVE".equals(phase)) verifyProspectiveBindings(experiment, definition, candidateSet, dataManifest, store, executorIdentity);

        Map<String, ArrayNode> sourceRows = rowsByAsset(decoded, requiredAssets); for (String asset : requiredAssets) if (sourceRows.get(asset) == null || sourceRows.get(asset).isEmpty()) throw new IllegalArgumentException("feature store has no rows for required asset " + asset);
        Map<String, ArrayNode> windowRows = new LinkedHashMap<>(sourceRows); if (!"WALK_FORWARD_OOS".equals(phase)) { JsonNode window = "PROSPECTIVE_LIVE".equals(phase) ? chronology.get("monitoring_window") : "EXPOSED_CONFIRMATION".equals(phase) ? firstDefined(chronology, "confirmation_window", "evaluation_window") : firstDefined(chronology, "evaluation_window", "development_window", "training_window"); if (window == null) throw new IllegalArgumentException(phase + " requires a declared evaluation window"); windowRows = new LinkedHashMap<>(); for (String asset : requiredAssets) windowRows.put(asset, rowsInWindow(sourceRows.get(asset), window, asset + ".evaluation_window", "PROSPECTIVE_LIVE".equals(phase))); }
        for (String asset : requiredAssets) if (windowRows.get(asset).isEmpty()) throw new IllegalArgumentException("declared evaluation window has no rows for required asset " + asset);

        Map<String, JsonNode> manifestIdentity = manifestIdentities(dataManifest); List<JsonNode> candidates = rows(candidateSet.get("candidates")); Map<String, JsonNode> candidateById = new LinkedHashMap<>(), normalized = new LinkedHashMap<>(); Map<String, ObjectNode> candidateFailures = new LinkedHashMap<>(), assetFailures = new LinkedHashMap<>(); ArrayNode intent = JSON.arrayNode(); Map<String, List<JsonNode>> intentByCandidate = new LinkedHashMap<>();
        boolean frozenPhase = Set.of("EXPOSED_CONFIRMATION", "PROSPECTIVE_LIVE").contains(phase); ObjectNode frozen = frozenPhase ? LegacyResearchV2.validateFrozenSelection(experiment, definition, candidateSet) : null; Map<String, String> frozenByAsset = frozen == null ? Map.of() : selectionMap(frozen.get("selections"));
        for (JsonNode candidate : candidates) { String candidateId = text(candidate.get("candidate_id")); candidateById.put(candidateId, candidate); String capability = adapterCapability(candidate); if (capability != null) { candidateFailures.put(candidateId, failure("EXECUTOR_CAPABILITY_UNAVAILABLE", capability)); continue; } try { ObjectNode definitionInput = candidate.path("definition").isObject() ? objectCopy(candidate.get("definition"), "candidate.definition") : objectCopy(candidate, "candidate"); definitionInput.put("id", candidateId); normalized.put(candidateId, SwingEngine.normalizeCandidate(definitionInput)); } catch (RuntimeException error) { candidateFailures.put(candidateId, failure("EXECUTOR_REJECTED", message(error))); continue; } if ("DEVELOPMENT".equals(phase)) { List<JsonNode> candidateIntent = new ArrayList<>(); for (String asset : requiredAssets) { ArrayNode signalIntent = SwingEngine.candidateSignalIntent(sortedRows(windowRows.get(asset)), normalized.get(candidateId)); ObjectNode entry = JSON.objectNode().put("candidate_id", candidateId).put("asset", asset); entry.set("rows", signalIntent); intent.add(entry); for (JsonNode row : signalIntent) { ObjectNode withAsset = objectCopy(row, "intent"); withAsset.put("asset", asset); candidateIntent.add(withAsset); } } intentByCandidate.put(candidateId, candidateIntent); } }

        Map<String, List<String>> behaviorGroups = new LinkedHashMap<>(); int runtimeK = 1;
        if (frozen != null) { for (JsonNode alias : rows(frozen.get("aliases"))) { List<String> ids = new ArrayList<>(); for (JsonNode id : rows(alias.get("candidate_ids"))) ids.add(text(id)); behaviorGroups.put(text(alias.get("behavior_sha256")), ids); } runtimeK = frozen.path("behavioralK").asInt(1); }
        else if ("DEVELOPMENT".equals(phase)) { for (var entry : intentByCandidate.entrySet()) { ObjectNode fpOptions = JSON.objectNode(); fpOptions.set("intentRows", arrayOf(entry.getValue())); String fingerprint = LegacyResearchV2.behavioralFingerprint(fpOptions); behaviorGroups.computeIfAbsent(fingerprint, ignored -> new ArrayList<>()).add(entry.getKey()); } runtimeK = Math.max(1, behaviorGroups.size()); }

        Evaluation state = new Evaluation(requiredAssets, candidates, normalized, candidateFailures, assetFailures, manifestIdentity, sourceRows, windowRows, chronology, experiment, adapter, executorConfig, seed, runtimeK);
        if ("WALK_FORWARD_OOS".equals(phase)) evaluateWalkForward(state, candidateSet, dataManifest, behaviorGroups);
        else evaluateWindow(state, frozenByAsset);
        runtimeK = state.runtimeK;
        completeMissingRows(state); markSelections(state, frozenByAsset);

        ArrayNode allTrades = sortedTrades(state.allTrades), selectedTrades = JSON.arrayNode(); for (JsonNode trade : allTrades) if (state.selectedByAsset.getOrDefault(text(trade.get("asset")), Set.of()).contains(text(trade.get("candidate_id")))) selectedTrades.add(cloneNode(trade)); selectedTrades = sortedTrades(selectedTrades);
        ObjectNode maxStatistic = maxStatistic(behaviorGroups, allTrades, chronology, runtimeK); for (JsonNode raw : state.metricRows) { ObjectNode row = (ObjectNode) raw, metrics = (ObjectNode) row.get("metrics"); boolean selected = state.selectedByAsset.getOrDefault(text(row.get("asset")), Set.of()).contains(text(row.get("candidate_id"))); row.put("selected", selected); metrics.put("selected", selected).put("candidate_count", runtimeK); Double expectancy = nullableNumber(metrics.get("expectancy_r")); putNullableNumber(metrics, "search_adjusted_expectancy_r", expectancy == null ? null : LegacyResearchV2.searchAdjustedExpectancyHeuristic(expectancy, jsNumber(metrics.get("completed_trades")), runtimeK)); ((ObjectNode) metrics.get("robust_stats")).set("max_statistic_p_value", cloneNode(maxStatistic.get("max_statistic_p_value"))); }
        ArrayNode globalRows = JSON.arrayNode(); for (JsonNode row : state.metricRows) if (frozen == null || frozenByAsset.get(text(row.get("asset"))).equals(text(row.get("candidate_id")))) globalRows.add(cloneNode(row)); ObjectNode globalOptions = JSON.objectNode().put("behavioralK", runtimeK); globalOptions.set("trades", allTrades); globalOptions.set("bars", decoded); ObjectNode global = LegacyResearchV2.computeGlobalRobustness(globalRows, globalOptions);
        JsonNode stress = selectedTrades.isEmpty() ? noSelectedStress(experiment) : LegacyResearchV2.runStressSuite(selectedTrades, experiment.path("acceptance").get("stress")); validateProspectiveTrades(phase, chronology, selectedTrades);
        ArrayNode marks = portfolioMarks(decoded, requiredAssets, manifestIdentity); ObjectNode portfolio = simulatePortfolio(experiment, chronology, selectedTrades, marks); String selectedTradesHash = LegacyResearchV2.hash(selectedTrades), portfolioSourceHash = portfolioSourceHash(experiment, chronology, selectedTradesHash, marks);

        ArrayNode perAsset = decisions(state, candidateFailures, assetFailures); List<String> portfolioReasons = new ArrayList<>(); if (selectedTrades.isEmpty()) portfolioReasons.add("NO_SELECTED_TRADES"); if (!stress.path("pass").asBoolean(false)) portfolioReasons.add("STRESS_REJECTED"); if (!portfolio.path("pass").asBoolean(false)) portfolioReasons.add("PORTFOLIO_REJECTED"); ObjectNode portfolioDecision = JSON.objectNode().put("status", portfolioReasons.isEmpty() ? "SHADOW" : "REJECTED"); portfolioDecision.set("reasons", strings(portfolioReasons.isEmpty() ? List.of("RESEARCH_EVIDENCE_ONLY") : portfolioReasons));
        ArrayNode aliasRows = JSON.arrayNode(); behaviorGroups.forEach((behavior, ids) -> { ObjectNode alias = JSON.objectNode().put("behavior_sha256", behavior); List<String> sorted = ids.stream().distinct().sorted().toList(); alias.set("candidate_ids", strings(sorted)); aliasRows.add(alias); });
        ObjectNode reconciliation = JSON.objectNode().put("candidate_trade_set_sha256", candidateTradeSetHash(state.metricRows, allTrades)).put("all_trades_sha256", LegacyResearchV2.hash(allTrades)).put("selected_trades_sha256", selectedTradesHash).put("derived_metrics_sha256", LegacyResearchV2.hash(state.metricRows)).put("stress_result_sha256", LegacyResearchV2.hash(stress)).put("portfolio_source_sha256", portfolioSourceHash).put("portfolio_result_sha256", LegacyResearchV2.hash(portfolio));
        ObjectNode payload = JSON.objectNode().put("schema", LegacyResearchV2.EVIDENCE_BUNDLE_SCHEMA).put("bundle_version", 1).put("provenance", "AUTHORITATIVE_RECOMPUTED").put("evidence_phase", phase).put("experiment_id", text(experiment.get("experiment_id"))).put("strategy_id", text(definition.get("strategy_id"))).put("precommit_sha256", LegacyResearchV2.hash(precommit)).put("definition_sha256", LegacyResearchV2.hash(definition)).put("experiment_sha256", LegacyResearchV2.hash(experiment)).put("candidate_set_sha256", LegacyResearchV2.hash(candidateSet)).put("data_manifest_sha256", optionText(dataManifest, "content_sha256", LegacyResearchV2.ownHash(dataManifest))).put("feature_store_sha256", text(store.get("features_sha256")));
        payload.set("required_assets", strings(requiredAssets)); ObjectNode artifacts = JSON.objectNode(); putPathOrNull(artifacts, "feature_store_path", options.get("featureStorePath")); artifacts.put("feature_store_artifact_sha256", text(executor.get("feature_store_artifact_sha256"))); putPathOrNull(artifacts, "data_manifest_path", options.get("dataManifestPath")); artifacts.put("data_manifest_artifact_sha256", text(executor.get("data_manifest_artifact_sha256"))); payload.set("input_artifacts", artifacts); ObjectNode finalExecutor = executor.deepCopy(); finalExecutor.put("identity_sha256", executorIdentity); payload.set("executor", finalExecutor); ObjectNode accounting = JSON.objectNode().put("declared_k", jsNumber(candidateSet.get("declared_k"))).put("syntactic_effective_k", jsNumber(candidateSet.get("effective_k"))).put("runtime_behavioral_k", runtimeK); accounting.set("aliases", aliasRows); payload.set("candidate_accounting", accounting); payload.set("metrics", state.metricRows); payload.set("trades", allTrades); payload.set("selected_trades", selectedTrades); payload.set("intent", intent); payload.set("fold_artifacts", state.foldArtifacts); payload.set("global_robustness", global); ObjectNode reality = maxStatistic.deepCopy(); reality.put("hypothesis_set", "behavioral_representatives_only").put("heuristic_search_adjustment", "descriptive; not a complete multiple-testing correction"); payload.set("statistical_reality_check", reality); payload.set("stress", cloneNode(stress)); payload.set("portfolio", portfolio); payload.set("reconciliation", reconciliation); ObjectNode decisions = JSON.objectNode(); decisions.set("per_asset", perAsset); decisions.set("portfolio", portfolioDecision); payload.set("decisions", decisions); payload.set("failures", failures(candidateFailures, assetFailures, requiredAssets)); payload.set("activation", JSON.objectNode().put("authorized", false).put("status", "SHADOW").put("reason", "Authoritative evidence is research-only; activation is a separate governed decision.")); return LegacyResearchV2.withHash(payload);
    }

    static void validatePortfolioRecomputation(JsonNode bundle, JsonNode experiment,
                                                 JsonNode suppliedManifest, JsonNode suppliedStore) {
        if (!present(experiment) || rows(bundle.get("selected_trades")).isEmpty()) return;
        JsonNode manifest = suppliedManifest;
        JsonNode store = suppliedStore;
        JsonNode artifacts = bundle.get("input_artifacts");
        if (!present(manifest) && present(artifacts == null ? null : artifacts.get("data_manifest_path"))) {
            manifest = readJson(Path.of(text(artifacts.get("data_manifest_path"))));
        }
        if (!present(store) && present(artifacts == null ? null : artifacts.get("feature_store_path"))) {
            Path path = Path.of(text(artifacts.get("feature_store_path"))).toAbsolutePath().normalize();
            com.tradinganalytics.infrastructure.security.PathConfinement.validateSinglyLinkedFile(path, "feature-store artifact");
            try { store = SwingEngine.readFeatureStoreArtifact(path); }
            catch (IOException error) { throw new IllegalArgumentException("feature-store artifact cannot be read", error); }
        }
        if (!present(store) || !present(manifest)) throw new IllegalArgumentException("authoritative portfolio marks/data source are unavailable for recomputation");
        if (!SwingEngine.verifyFeatureStoreHash(store)) throw new IllegalArgumentException("feature-store content hash mismatch");
        ArrayNode decoded = SwingEngine.decodeFeatureStore(store);
        List<String> assets = new ArrayList<>(); for (JsonNode asset : rows(bundle.get("required_assets"))) assets.add(assetName(asset));
        ArrayNode marks = portfolioMarks(decoded, assets, manifestIdentities(manifest));
        String expectedSource = portfolioSourceHash(experiment, experiment.path("evaluation_chronology"), LegacyResearchV2.hash(bundle.get("selected_trades")), marks);
        if (!expectedSource.equals(text(bundle.path("reconciliation").get("portfolio_source_sha256")))) throw new IllegalArgumentException("evidence bundle portfolio source reconciliation mismatch");
        ObjectNode recomputed = simulatePortfolio(experiment, experiment.path("evaluation_chronology"), arrayOf(rows(bundle.get("selected_trades"))), marks);
        if (!LegacyResearchV2.hash(recomputed).equals(LegacyResearchV2.hash(bundle.get("portfolio")))) throw new IllegalArgumentException("evidence bundle portfolio is not recomputed from canonical trades/marks");
    }

    static void validateAuthoritativeMetricRows(JsonNode bundle, JsonNode experiment,
                                                 JsonNode candidateSet, JsonNode suppliedManifest,
                                                 JsonNode suppliedStore) {
        if (!present(experiment) || !present(candidateSet)) return;
        JsonNode manifest = suppliedManifest;
        JsonNode store = suppliedStore;
        JsonNode artifacts = bundle.get("input_artifacts");
        if (!present(manifest) && present(artifacts == null ? null : artifacts.get("data_manifest_path"))) manifest = readJson(Path.of(text(artifacts.get("data_manifest_path"))));
        if (!present(store) && present(artifacts == null ? null : artifacts.get("feature_store_path"))) {
            Path path = Path.of(text(artifacts.get("feature_store_path"))).toAbsolutePath().normalize();
            com.tradinganalytics.infrastructure.security.PathConfinement.validateSinglyLinkedFile(path, "feature-store artifact");
            try { store = SwingEngine.readFeatureStoreArtifact(path); }
            catch (IOException error) { throw new IllegalArgumentException("feature-store artifact cannot be read", error); }
        }
        if (present(store) && !SwingEngine.verifyFeatureStoreHash(store)) throw new IllegalArgumentException("feature-store content hash verification failed during metric reconciliation");
        ArrayNode decoded = present(store) ? SwingEngine.decodeFeatureStore(store) : JSON.arrayNode();
        if (present(manifest) && !decoded.isEmpty()) validateManifestIdentities(decoded, manifest);

        JsonNode chronology = experiment.path("evaluation_chronology");
        List<String> requiredAssets = new ArrayList<>(); for (JsonNode value : rows(experiment.get("required_assets"))) requiredAssets.add(assetName(value));
        Map<String, Integer> periodBars = new LinkedHashMap<>();
        for (String asset : requiredAssets) periodBars.put(asset, (int) rows(decoded).stream().filter(row -> asset.equals(lower(row.get("asset")))).count());
        if (!decoded.isEmpty() && !"WALK_FORWARD_OOS".equals(text(experiment.get("evidence_phase")))) {
            JsonNode window = "PROSPECTIVE_LIVE".equals(text(experiment.get("evidence_phase"))) ? chronology.get("monitoring_window") : "EXPOSED_CONFIRMATION".equals(text(experiment.get("evidence_phase"))) ? firstDefined(chronology, "confirmation_window", "evaluation_window") : firstDefined(chronology, "evaluation_window", "development_window", "training_window");
            if (present(window)) { long start = time(window.get("start")), end = time(window.get("end")); for (String asset : requiredAssets) periodBars.put(asset, (int) rows(decoded).stream().filter(row -> asset.equals(lower(row.get("asset"))) && jsTime(row.get("time")) >= start && jsTime(row.get("time")) < end).count()); }
        } else if (!decoded.isEmpty()) {
            Map<String, Set<String>> times = new LinkedHashMap<>(); requiredAssets.forEach(asset -> times.put(asset, new LinkedHashSet<>()));
            for (JsonNode fold : rows(chronology.get("folds"))) { JsonNode window = firstDefined(fold, "test", "oos", "test_window"); if (!present(window)) continue; long start = time(window.get("start")), end = time(window.get("end")); for (JsonNode row : decoded) { String asset = lower(row.get("asset")); if (times.containsKey(asset) && jsTime(row.get("time")) >= start && jsTime(row.get("time")) < end) times.get(asset).add(text(row.get("time"))); } }
            times.forEach((asset, values) -> periodBars.put(asset, values.size()));
        }

        Map<String, JsonNode> candidateById = new LinkedHashMap<>(); for (JsonNode candidate : rows(candidateSet.get("candidates"))) candidateById.put(text(candidate.get("candidate_id")), candidate);
        int runtimeK = bool(bundle.path("candidate_accounting").get("runtime_behavioral_k")) ? (int) jsNumber(bundle.path("candidate_accounting").get("runtime_behavioral_k")) : (int) jsNumber(candidateSet.get("effective_k"));
        int seed = rows(chronology.get("seeds")).isEmpty() ? 1 : (int) jsNumber(rows(chronology.get("seeds")).get(0));
        for (JsonNode row : rows(bundle.get("metrics"))) {
            String candidateId = text(row.get("candidate_id")), asset = lower(row.get("asset")); JsonNode candidate = candidateById.get(candidateId);
            if (candidate == null) throw new IllegalArgumentException("evidence bundle metric references unknown candidate " + candidateId);
            ObjectNode normalized;
            try { normalized = candidate.path("definition").isObject() ? objectCopy(candidate.get("definition"), "candidate.definition") : JSON.objectNode(); normalized.put("id", candidateId); normalized = SwingEngine.normalizeCandidate(normalized); }
            catch (RuntimeException error) { boolean hasTrades = rows(bundle.get("trades")).stream().anyMatch(trade -> candidateId.equals(text(trade.get("candidate_id")))); if (!hasTrades && present(row.path("execution").get("failure"))) continue; throw new IllegalArgumentException("metric reconciliation candidate " + candidateId + " is not executable: " + message(error)); }
            ArrayNode scoped = JSON.arrayNode(); for (JsonNode trade : rows(bundle.get("trades"))) if (candidateId.equals(text(trade.get("candidate_id"))) && asset.equals(lower(trade.get("asset")))) scoped.add(cloneNode(trade));
            Integer bars = periodBars.getOrDefault(asset, 0) == 0 ? null : periodBars.get(asset);
            ObjectNode expected = authoritativeMetric(candidateId, asset, scoped, runtimeK, jsNumber(normalized.get("initial_equity")), bars, seed);
            ObjectNode supplied = row.path("metrics").isObject() ? objectCopy(row.get("metrics"), "metric") : JSON.objectNode();
            supplied.remove("selected"); expected.remove("selected");
            if (supplied.path("robust_stats").isObject()) ((ObjectNode) supplied.get("robust_stats")).remove("max_statistic_p_value");
            if (expected.path("robust_stats").isObject()) ((ObjectNode) expected.get("robust_stats")).remove("max_statistic_p_value");
            if (decoded.isEmpty()) { supplied.remove("exposure"); expected.remove("exposure"); }
            if (!stable(supplied).equals(stable(expected))) throw new IllegalArgumentException("evidence bundle authoritative metric mismatch for " + candidateId + "/" + text(row.get("asset")));
        }
        if (bundle.path("statistical_reality_check").has("max_statistic_p_value")) { JsonNode maximum = bundle.path("statistical_reality_check").get("max_statistic_p_value"); for (JsonNode row : rows(bundle.get("metrics"))) if (!Objects.equals(row.path("metrics").path("robust_stats").get("max_statistic_p_value"), maximum)) throw new IllegalArgumentException("evidence bundle max-statistic mismatch for " + text(row.get("candidate_id")) + "/" + text(row.get("asset"))); }
    }

    private static void evaluateWindow(Evaluation state, Map<String, String> frozenByAsset) {
        Set<String> evaluationIds = frozenByAsset.isEmpty() ? state.normalized.keySet() : new LinkedHashSet<>(frozenByAsset.values());
        for (JsonNode candidate : state.candidates) { String id = text(candidate.get("candidate_id")); if (!evaluationIds.contains(id)) continue; JsonNode normalized = state.normalized.get(id); for (String asset : state.assets) { ArrayNode series = sortedRows(state.windowRows.get(asset)); if (!frozenByAsset.isEmpty() && !id.equals(frozenByAsset.get(asset))) { state.metricRows.add(metricRow(id, asset, false, "NOT_FROZEN_FOR_ASSET", state.adapter, authoritativeMetric(id, asset, JSON.arrayNode(), state.runtimeK, initialEquity(normalized, state.experiment), Math.max(1, series.size()), state.seed), failure("NOT_FROZEN_FOR_ASSET", "candidate is not frozen for this asset"))); continue; } if (normalized == null) continue; JsonNode instrument; try { instrument = instrumentFor(candidate, asset, state.manifestIdentity); } catch (RuntimeException error) { state.assetFailures.put(id + "|" + asset, failure("INSTRUMENT_CONTRACT_UNAVAILABLE", message(error))); continue; } ObjectNode report = SwingEngine.evaluateCandidate(series, normalized, evalOptions(state.runtimeK, state.executorConfig)); ArrayNode trades = state.addTrades(id, asset, report.path("trades"), instrument); state.metricRows.add(metricRow(id, asset, false, "EVALUATED", state.adapter, authoritativeMetric(id, asset, trades, state.runtimeK, initialEquity(normalized, state.experiment), Math.max(1, series.size()), state.seed), null)); } }
        if (!frozenByAsset.isEmpty()) for (String asset : state.assets) state.selectedByAsset.put(asset, new LinkedHashSet<>(List.of(frozenByAsset.get(asset))));
        else for (String asset : state.assets) { List<JsonNode> reports = new ArrayList<>(); for (JsonNode row : state.metricRows) if (asset.equals(text(row.get("asset")))) reports.add(row); JsonNode gate = firstDefined(state.chronology, "selection_gate", "train_gate"); if (gate == null) gate = firstDefined(state.experiment.path("acceptance"), "selection_gate", "minimums"); if (gate == null) gate = JSON.objectNode().put("require_finite", true); String winner = chooseWinner(reports, state.chronology, gate); if (winner != null) state.selectedByAsset.put(asset, new LinkedHashSet<>(List.of(winner))); }
    }

    private static void evaluateWalkForward(Evaluation state, JsonNode candidateSet, JsonNode dataManifest, Map<String, List<String>> behaviorGroups) {
        List<JsonNode> folds = rows(state.chronology.get("folds")); double barDuration = jsNumber(state.chronology.get("bar_duration_ms")); Map<String, Set<Long>> oosBars = new LinkedHashMap<>(); state.assets.forEach(asset -> oosBars.put(asset, new LinkedHashSet<>()));
        for (int foldIndex = 0; foldIndex < folds.size(); foldIndex++) { JsonNode fold = folds.get(foldIndex); verifyFoldArtifact(fold, foldIndex, state.experiment, candidateSet, dataManifest); JsonNode trainWindow = firstDefined(fold, "train", "training"), testWindow = firstDefined(fold, "test", "oos", "test_window"); long trainStart = time(trainWindow.get("start")), trainDeclaredEnd = time(trainWindow.get("end")), testStart = time(testWindow.get("start")), testEnd = time(testWindow.get("end")); double purge = fold.has("purge_bars") ? jsNumber(fold.get("purge_bars")) : numberOr(state.chronology.get("purge_bars"), 0), embargo = fold.has("embargo_bars") ? jsNumber(fold.get("embargo_bars")) : numberOr(state.chronology.get("embargo_bars"), 0); long trainEnd = Math.min(trainDeclaredEnd, (long) (testStart - (purge + embargo) * barDuration)); if (trainEnd < trainStart) throw new IllegalArgumentException("fold " + foldIndex + " purge/embargo removes the declared train window");
            Map<String, List<String>> foldGroups = new LinkedHashMap<>(); for (var entry : state.normalized.entrySet()) { List<JsonNode> intents = new ArrayList<>(); for (String asset : state.assets) { ArrayNode train = filter(state.sourceRows.get(asset), trainStart, trainEnd, false); for (JsonNode raw : SwingEngine.candidateSignalIntent(train, entry.getValue())) { ObjectNode row = objectCopy(raw, "intent"); row.put("asset", asset); intents.add(row); } } ObjectNode fp = JSON.objectNode(); fp.set("intentRows", arrayOf(intents)); foldGroups.computeIfAbsent(LegacyResearchV2.behavioralFingerprint(fp), ignored -> new ArrayList<>()).add(entry.getKey()); } int foldK = Math.max(1, foldGroups.size()); if (foldK > state.runtimeK) { state.runtimeK = foldK; behaviorGroups.clear(); behaviorGroups.putAll(foldGroups); }
            ObjectNode foldRecord = JSON.objectNode().put("fold_index", foldIndex).put("effective_train_end", trainEnd).put("purge_bars", purge).put("embargo_bars", embargo).put("runtime_behavioral_k", foldK); foldRecord.set("train", windowNode(trainStart, trainDeclaredEnd)); foldRecord.set("test", windowNode(testStart, testEnd)); ArrayNode aliases = JSON.arrayNode(); foldGroups.forEach((behavior, ids) -> { ObjectNode alias = JSON.objectNode().put("behavior_sha256", behavior); alias.set("candidate_ids", strings(ids.stream().sorted().toList())); aliases.add(alias); }); foldRecord.set("behavioral_aliases", aliases); ObjectNode trainSelection = JSON.objectNode(); ArrayNode testCandidates = JSON.arrayNode();
            for (String asset : state.assets) { ArrayNode train = filter(state.sourceRows.get(asset), trainStart, trainEnd, false), test = filter(state.sourceRows.get(asset), testStart, testEnd, false); for (JsonNode row : test) oosBars.get(asset).add(row.path("time").asLong()); if (train.isEmpty() || test.isEmpty()) { trainSelection.set(asset, JSON.objectNode().put("status", "REJECTED").put("reason", "INSUFFICIENT_DECLARED_WINDOW_ROWS")); continue; } List<JsonNode> reports = new ArrayList<>(); for (var entry : state.normalized.entrySet()) { ObjectNode report = SwingEngine.evaluateCandidate(train, entry.getValue(), evalOptions(foldK, state.executorConfig)); ObjectNode selectionRow = JSON.objectNode().put("candidate_id", entry.getKey()); selectionRow.set("candidate", cloneNode(entry.getValue())); selectionRow.set("metrics", cloneNode(report.get("metrics"))); reports.add(selectionRow); } JsonNode gate = firstDefined(state.chronology, "selection_gate", "train_gate"); if (gate == null) gate = state.experiment.path("acceptance").get("fold_selection_gate"); String winner = chooseWinner(reports, state.chronology, gate); ObjectNode selection = JSON.objectNode().put("status", winner == null ? "REJECTED" : "SELECTED"); if (winner == null) selection.putNull("candidate_id").put("reason", "NO_TRAIN_CANDIDATE_PASSES_FROZEN_GATE"); else selection.put("candidate_id", winner).putNull("reason"); selection.put("objective", objectiveName(state.chronology.get("selection_objective"))); ArrayNode eligible = JSON.arrayNode(); if (winner != null) eligible.add(winner); selection.set("eligible", eligible); ArrayNode metrics = JSON.arrayNode(); reports.forEach(metrics::add); selection.set("metrics", metrics); trainSelection.set(asset, selection); if (winner == null) continue; state.selectedByAsset.computeIfAbsent(asset, ignored -> new LinkedHashSet<>()).add(winner); JsonNode candidate = state.candidates.stream().filter(row -> winner.equals(text(row.get("candidate_id")))).findFirst().orElse(null); JsonNode instrument; try { instrument = instrumentFor(candidate, asset, state.manifestIdentity); } catch (RuntimeException error) { state.assetFailures.put(winner + "|" + asset, failure("INSTRUMENT_CONTRACT_UNAVAILABLE", message(error))); continue; } ObjectNode testReport = SwingEngine.evaluateCandidate(test, state.normalized.get(winner), evalOptions(foldK, state.executorConfig)); ArrayNode trades = state.addTrades(winner, asset, testReport.path("trades"), instrument); ObjectNode testRow = JSON.objectNode().put("asset", asset).put("candidate_id", winner); ArrayNode ids = JSON.arrayNode(); for (JsonNode trade : trades) ids.add(text(trade.get("trade_id"))); testRow.set("trades", ids); testRow.set("metrics", authoritativeMetric(winner, asset, trades, state.runtimeK, initialEquity(state.normalized.get(winner), state.experiment), Math.max(1, test.size()), state.seed)); testCandidates.add(testRow); }
            foldRecord.set("train_selection", trainSelection); foldRecord.set("test_candidates", testCandidates); state.foldArtifacts.add(foldRecord);
        }
        for (JsonNode candidate : state.candidates) for (String asset : state.assets) { String id = text(candidate.get("candidate_id")), key = id + "|" + asset; ArrayNode trades = state.tradesByPair.getOrDefault(key, JSON.arrayNode()); boolean selected = state.selectedByAsset.getOrDefault(asset, Set.of()).contains(id); ObjectNode row = metricRow(id, asset, selected, selected ? "OOS_SELECTED_BY_TRAIN" : "NOT_SELECTED_IN_DECLARED_FOLDS", state.adapter, authoritativeMetric(id, asset, trades, state.runtimeK, initialEquity(state.normalized.get(id), state.experiment), oosBars.get(asset).isEmpty() ? null : oosBars.get(asset).size(), state.seed), null); ArrayNode trainingFolds = JSON.arrayNode(); for (JsonNode fold : state.foldArtifacts) if (id.equals(text(fold.path("train_selection").path(asset).get("candidate_id")))) trainingFolds.add(fold.get("fold_index")); row.set("training_folds", trainingFolds); state.metricRows.add(row); }
    }

    private static final class Evaluation {
        final List<String> assets; final List<JsonNode> candidates; final Map<String, JsonNode> normalized; final Map<String, ObjectNode> candidateFailures, assetFailures; final Map<String, JsonNode> manifestIdentity; final Map<String, ArrayNode> sourceRows, windowRows; final JsonNode chronology, experiment, executorConfig; final String adapter; final int seed; int runtimeK; final ArrayNode allTrades = JSON.arrayNode(), metricRows = JSON.arrayNode(), foldArtifacts = JSON.arrayNode(); final Map<String, ArrayNode> tradesByPair = new LinkedHashMap<>(); final Map<String, Set<String>> selectedByAsset = new LinkedHashMap<>();
        Evaluation(List<String> assets, List<JsonNode> candidates, Map<String, JsonNode> normalized, Map<String, ObjectNode> candidateFailures, Map<String, ObjectNode> assetFailures, Map<String, JsonNode> manifestIdentity, Map<String, ArrayNode> sourceRows, Map<String, ArrayNode> windowRows, JsonNode chronology, JsonNode experiment, String adapter, JsonNode executorConfig, int seed, int runtimeK) { this.assets = assets; this.candidates = candidates; this.normalized = normalized; this.candidateFailures = candidateFailures; this.assetFailures = assetFailures; this.manifestIdentity = manifestIdentity; this.sourceRows = sourceRows; this.windowRows = windowRows; this.chronology = chronology; this.experiment = experiment; this.adapter = adapter; this.executorConfig = executorConfig; this.seed = seed; this.runtimeK = runtimeK; }
        ArrayNode addTrades(String id, String asset, JsonNode rawTrades, JsonNode instrument) { List<JsonNode> canonical = new ArrayList<>(); int index = 0; for (JsonNode raw : rows(rawTrades)) canonical.add(canonicalTrade(raw, id, asset, index++, instrument)); canonical.sort(Comparator.comparingLong((JsonNode row) -> time(row.get("entry_time"))).thenComparing(row -> text(row.get("trade_id")))); ArrayNode result = arrayOf(canonical); ObjectNode validation = JSON.objectNode(); ArrayNode ids = JSON.arrayNode(); candidates.forEach(row -> ids.add(text(row.get("candidate_id")))); validation.set("candidateIds", ids); validation.set("assets", strings(assets)); LegacyResearchV2.validateCanonicalTrades(result, validation); result.forEach(allTrades::add); tradesByPair.computeIfAbsent(id + "|" + asset, ignored -> JSON.arrayNode()).addAll(result); return result; }
    }

    private static JsonNode firstDefined(JsonNode value, String... keys) { if (value == null) return null; for (String key : keys) if (value.has(key)) return value.get(key); return null; }
    private static JsonNode firstTruthy(JsonNode value, String... keys) { if (value == null) return null; for (String key : keys) { JsonNode candidate = value.get(key); if (bool(candidate)) return candidate; } return null; }
    private static boolean present(JsonNode value) { return value != null && !value.isNull() && !value.isMissingNode(); }
    private static String optionText(JsonNode value, String key, String fallback) { return value != null && value.has(key) && present(value.get(key)) ? text(value.get(key)) : fallback; }
    private static String assetName(JsonNode value) { return value != null && value.isObject() ? lower(firstTruthy(value, "asset", "symbol")) : lower(value); }
    private static double numberOr(JsonNode value, double fallback) { double number = jsNumber(value); return Double.isFinite(number) ? number : fallback; }
    private static long time(JsonNode value) { long result = jsTime(value); if (result == Long.MIN_VALUE) throw new IllegalArgumentException("timestamp must be a valid timestamp"); return result; }
    private static String message(Throwable error) { return error.getMessage() == null || error.getMessage().isEmpty() ? error.toString() : error.getMessage(); }
    private static ObjectNode failure(String code, String reason) { return JSON.objectNode().put("code", code).put("reason", reason); }
    private static Double nullableNumber(JsonNode value) { if (value == null || value.isNull()) return null; double number = jsNumber(value); return Double.isFinite(number) ? number : null; }
    private static void putNullableNumber(ObjectNode target, String key, Double value) { if (value == null || !Double.isFinite(value)) target.putNull(key); else target.put(key, value); }

    private static void validateManifestIdentities(ArrayNode decoded, JsonNode manifest) {
        Map<String, JsonNode> identities = manifestIdentities(manifest); for (JsonNode row : decoded) { JsonNode declared = identities.get(lower(row.get("asset"))); if (declared == null) continue; JsonNode rowVenue = firstTruthy(row, "venue", "exchange"), rowSymbol = firstTruthy(row, "symbol", "instrument_id", "instrument_symbol"); if (bool(rowVenue) && bool(declared.get("venue")) && !text(rowVenue).equals(text(declared.get("venue")))) throw new IllegalArgumentException("feature row venue identity mismatch for " + text(row.get("asset"))); if (bool(rowSymbol) && bool(declared.get("symbol")) && !text(rowSymbol).equals(text(declared.get("symbol")))) throw new IllegalArgumentException("feature row symbol identity mismatch for " + text(row.get("asset"))); }
        for (JsonNode dataset : rows(manifest.get("datasets"))) if (bool(dataset.get("asset")) && dataset.has("row_count")) { long actual = rows(decoded).stream().filter(row -> lower(dataset.get("asset")).equals(lower(row.get("asset")))).count(); if (actual != (long) jsNumber(dataset.get("row_count"))) throw new IllegalArgumentException("data manifest dataset row count mismatch: " + text(dataset.get("dataset_id"))); }
    }

    private static Map<String, JsonNode> manifestIdentities(JsonNode manifest) { Map<String, JsonNode> result = new LinkedHashMap<>(); for (JsonNode dataset : rows(manifest.get("datasets"))) if (bool(dataset.get("asset"))) { ObjectNode identity = JSON.objectNode(); JsonNode venue = firstTruthy(dataset, "trade_venue", "venue", "source_venue"), symbol = firstTruthy(dataset, "symbol", "instrument_id", "instrument_symbol"); if (venue == null) identity.putNull("venue"); else identity.set("venue", cloneNode(venue)); if (symbol == null) identity.putNull("symbol"); else identity.set("symbol", cloneNode(symbol)); result.put(lower(dataset.get("asset")), identity); } return result; }

    private static ObjectNode executor(String adapter, JsonNode config, JsonNode chronology, JsonNode store, JsonNode manifest, JsonNode options) {
        String swingHash = classHash(SwingEngine.class), evaluatorHash = classHash(LegacyResearchV2Evaluator.class), portfolioHash = classHash(LegacyResearchV2Evaluator.class); ObjectNode sources = JSON.objectNode().put("swing_engine", swingHash).put("authoritative_evaluator", evaluatorHash).put("portfolio_simulator", portfolioHash); ObjectNode code = JSON.objectNode().put("adapter", adapter).put("evaluator", "strategy-research-v2").put("portfolio", "strategy-portfolio"); code.set("executorConfig", cloneNode(config)); ObjectNode environment = JSON.objectNode().put("node", System.getProperty("java.version")).put("platform", System.getProperty("os.name")).put("arch", System.getProperty("os.arch"));
        ObjectNode out = JSON.objectNode().put("adapter_id", adapter).put("adapter_version", "1").put("source_file", "com.tradinganalytics.research.swing.SwingEngine").put("source_file_sha256", swingHash).put("code_config_sha256", LegacyResearchV2.hash(code)).put("feature_store_sha256", text(store.get("features_sha256"))).put("feature_store_artifact_sha256", artifactHash(options.get("featureStorePath"), store, "feature-store artifact")).put("data_manifest_sha256", optionText(manifest, "content_sha256", LegacyResearchV2.ownHash(manifest))).put("data_manifest_artifact_sha256", artifactHash(options.get("dataManifestPath"), manifest, "data-manifest artifact")).put("package_lock_sha256", classHash(LegacyResearchV2.class)).put("environment_sha256", LegacyResearchV2.hash(environment)).put("timezone", text(chronology.get("timezone"))).put("bar_convention", text(chronology.get("bar_convention"))).put("same_bar_collision_policy", optionText(config, "same_bar_collision", "stop-first")).put("cost_funding_assumptions", optionText(config, "cost_funding_assumptions", "executor-recorded fees/slippage/funding; no invented venue-independent execution")); out.set("source_files", sources); out.set("supported_instruments", strings(List.of("crypto spot", "linear perpetuals", "linear dated futures"))); out.set("supported_features", strings(List.of("completed OHLC bars", "mechanical score", "setup identity", "funding settlements"))); ObjectNode ledger = JSON.objectNode().put("bootstrap", jsNumber(chronology.path("seeds").get(0))).put("risk", jsNumber(chronology.path("seeds").get(0))); out.set("seed_ledger", ledger); return out;
    }

    private static String classHash(Class<?> type) { String resource = "/" + type.getName().replace('.', '/') + ".class"; try (InputStream input = type.getResourceAsStream(resource)) { if (input == null) return LegacyResearchSupport.hash(type.getName()); return LegacyResearchSupport.hash(input.readAllBytes()); } catch (IOException error) { throw new IllegalArgumentException("class bytecode cannot be hashed: " + type.getName(), error); } }
    private static String artifactHash(JsonNode path, JsonNode fallback, String label) { if (!bool(path)) return LegacyResearchV2.hash(fallback); byte[] bytes = com.tradinganalytics.infrastructure.security.PathConfinement.readSinglyLinkedFile(Path.of(text(path)).toAbsolutePath().normalize(), label); return LegacyResearchSupport.hash(bytes); }

    private static void verifyProspectiveBindings(JsonNode experiment, JsonNode definition, JsonNode candidateSet, JsonNode manifest, JsonNode store, String executorIdentity) { JsonNode chronology = experiment.get("evaluation_chronology"), frozen = firstDefined(chronology, "frozen_hashes", "frozen_bindings"), selection = firstDefined(chronology, "frozen_selection", "frozen_candidate_selection"); if (frozen == null || !text(frozen.get("candidate_set_sha256")).equals(LegacyResearchV2.hash(candidateSet)) || !text(frozen.get("definition_sha256")).equals(LegacyResearchV2.hash(definition)) || !text(frozen.get("experiment_sha256")).equals(prospectiveBindingHash(experiment)) || !text(frozen.get("data_manifest_sha256")).equals(optionText(manifest, "content_sha256", LegacyResearchV2.ownHash(manifest))) || !text(frozen.get("feature_store_sha256")).equals(text(store.get("features_sha256"))) || !text(frozen.get("executor_sha256")).equals(executorIdentity) || selection == null || !text(frozen.get("frozen_selection_sha256")).equals(text(selection.get("selection_sha256")))) throw new IllegalArgumentException("prospective frozen hash binding mismatch"); }
    private static String prospectiveBindingHash(JsonNode experiment) { ObjectNode copy = objectCopy(experiment, "experiment"); copy.remove("content_sha256"); JsonNode chronologyNode = copy.get("evaluation_chronology"); if (chronologyNode != null && chronologyNode.isObject()) { ObjectNode chronology = (ObjectNode) chronologyNode; chronology.remove("folds"); for (String key : List.of("frozen_hashes", "frozen_bindings")) if (chronology.path(key).isObject()) { ObjectNode binding = (ObjectNode) chronology.get(key); binding.remove("experiment_sha256"); if (binding.isEmpty()) chronology.remove(key); } if (chronology.path("frozen_selection").isObject()) ((ObjectNode) chronology.get("frozen_selection")).remove(List.of("experiment_sha256", "selection_sha256")); } return LegacyResearchV2.hash(copy); }

    private static Map<String, ArrayNode> rowsByAsset(ArrayNode rows, List<String> assets) { Map<String, ArrayNode> result = new LinkedHashMap<>(); assets.forEach(asset -> result.put(asset, JSON.arrayNode())); for (JsonNode row : rows) { String asset = lower(row.get("asset")); if (result.containsKey(asset)) result.get(asset).add(cloneNode(row)); } result.replaceAll((asset, values) -> sortedRows(values)); return result; }
    private static ArrayNode sortedRows(JsonNode values) { List<JsonNode> rows = new ArrayList<>(rows(values)); rows.sort(Comparator.comparingDouble(row -> jsNumber(row.get("time")))); return arrayOf(rows); }
    private static ArrayNode rowsInWindow(JsonNode values, JsonNode window, String name, boolean inclusiveEnd) { long start = time(window.get("start")), end = time(window.get("end")); if (!(start < end)) throw new IllegalArgumentException(name + " must be increasing"); return filter(values, start, end, inclusiveEnd); }
    private static ArrayNode filter(JsonNode values, long start, long end, boolean inclusiveEnd) { ArrayNode result = JSON.arrayNode(); for (JsonNode row : rows(values)) { long at = time(row.get("time")); if (at >= start && (inclusiveEnd ? at <= end : at < end)) result.add(cloneNode(row)); } return sortedRows(result); }
    private static Map<String, String> selectionMap(JsonNode selections) { Map<String, String> result = new LinkedHashMap<>(); for (JsonNode row : rows(selections)) result.put(text(row.get("asset")), text(row.get("candidate_id"))); return result; }

    private static String adapterCapability(JsonNode candidate) { JsonNode definition = candidate.path("definition").isObject() ? candidate.get("definition") : candidate; String method = optionText(definition, "method", optionText(definition, "strategy_method", optionText(definition, "execution_model", ""))).toLowerCase(Locale.ROOT); for (String token : List.of("option", "options", "multi-leg", "multileg", "basis", "carry", "hft", "arbitrage", "order-book", "queue")) if (method.contains(token)) return "UNSUPPORTED_SPECIALIZED_METHOD:" + method; JsonNode instrument = candidateInstrument(candidate, null); String type = lower(firstTruthy(instrument, "instrument_type", "type")); return Set.of("option", "options", "basis", "carry", "funding").contains(type) ? "UNSUPPORTED_INSTRUMENT:" + type : null; }
    private static JsonNode candidateInstrument(JsonNode candidate, String asset) { JsonNode definition = candidate.path("definition").isObject() ? candidate.get("definition") : candidate, contract = firstDefined(definition, "instrument_contract", "tradable_instrument_contract"); List<JsonNode> instruments = new ArrayList<>(); if (contract != null) for (JsonNode item : rows(firstDefined(contract, "instruments", "assets"))) { if (item.isTextual()) instruments.add(JSON.objectNode().put("asset", text(item)).put("asset_class", "crypto").put("instrument_type", "spot")); else instruments.add(item); } if (instruments.isEmpty()) for (JsonNode item : rows(definition.get("instruments"))) instruments.add(item); if (instruments.isEmpty() && present(definition.get("instrument"))) instruments.add(definition.get("instrument")); if (asset != null) return instruments.stream().filter(item -> asset.equals(lower(firstTruthy(item, "asset", "symbol")))).findFirst().orElse(null); if (!instruments.isEmpty()) return instruments.get(0); ObjectNode fallback = JSON.objectNode(); fallback.set("asset", cloneNode(definition.get("asset"))); fallback.put("asset_class", "crypto").put("instrument_type", "spot"); return fallback; }
    private static JsonNode instrumentFor(JsonNode candidate, String asset, Map<String, JsonNode> identities) { JsonNode source = candidateInstrument(candidate, asset); String candidateId = text(candidate.get("candidate_id")); if (source == null) throw new IllegalArgumentException("candidate " + candidateId + " has no instrument contract for " + asset); ObjectNode instrument = objectCopy(source, "instrument"); JsonNode declared = identities.getOrDefault(asset, JSON.objectNode()), explicitVenue = firstTruthy(instrument, "venue", "exchange"), explicitSymbol = firstTruthy(instrument, "symbol", "instrument_id"); if (bool(explicitVenue) && bool(declared.get("venue")) && !text(explicitVenue).equals(text(declared.get("venue")))) throw new IllegalArgumentException("candidate " + candidateId + " venue does not match data manifest for " + asset); if (bool(explicitSymbol) && bool(declared.get("symbol")) && !text(explicitSymbol).equals(text(declared.get("symbol")))) throw new IllegalArgumentException("candidate " + candidateId + " symbol does not match data manifest for " + asset); if (!bool(firstTruthy(instrument, "venue", "exchange")) && bool(declared.get("venue"))) instrument.set("venue", cloneNode(declared.get("venue"))); if (!bool(firstTruthy(instrument, "symbol", "instrument_id")) && bool(declared.get("symbol"))) instrument.set("symbol", cloneNode(declared.get("symbol"))); return instrument; }

    private static ObjectNode evalOptions(int candidateCount, JsonNode config) { return JSON.objectNode().put("candidate_count", candidateCount).put("same_bar_collision", optionText(config, "same_bar_collision", "stop-first")).put("bootstrap_rounds", 0); }
    private static double initialEquity(JsonNode normalized, JsonNode experiment) { if (normalized != null && bool(normalized.get("initial_equity"))) return jsNumber(normalized.get("initial_equity")); if (bool(experiment.get("initial_equity"))) return jsNumber(experiment.get("initial_equity")); if (bool(experiment.path("portfolio_policy").get("initial_equity"))) return jsNumber(experiment.path("portfolio_policy").get("initial_equity")); return 100_000; }
    private static ObjectNode metricRow(String candidateId, String asset, boolean selected, String status, String adapter, ObjectNode metrics, ObjectNode failure) { ObjectNode row = JSON.objectNode().put("candidate_id", candidateId).put("asset", asset).put("selected", selected); ObjectNode execution = JSON.objectNode().put("status", status).put("adapter", adapter); if (failure != null) { ObjectNode scoped = failure.deepCopy(); scoped.put("scope", "CANDIDATE_ASSET").put("candidate_id", candidateId).put("asset", asset); execution.set("failure", scoped); } row.set("execution", execution); row.set("metrics", metrics); return row; }

    private static ObjectNode authoritativeMetric(String candidateId, String asset, JsonNode trades, int candidateCount, double initialEquity, Integer periodBars, int seed) { ArrayNode ordered = sortedTrades(trades); List<Double> values = new ArrayList<>(); double grossWin = 0, grossLoss = 0, totalPnl = 0, turnover = 0, heldBars = 0; int wins = 0, losses = 0; for (JsonNode trade : ordered) { double value = jsNumber(trade.get("net_r")), pnl = numberOr(trade.get("net_pnl"), 0); if (Double.isFinite(value)) { values.add(value); if (value > 0) wins++; else if (value < 0) losses++; } grossWin += Math.max(0, pnl); grossLoss += Math.abs(Math.min(0, pnl)); totalPnl += pnl; turnover += Math.abs(numberOr(trade.get("notional"), 0)) * 2; heldBars += Math.max(0, numberOr(trade.get("hold_bars"), 0)); } Double mean = values.isEmpty() ? null : jsMean(values); Double profitFactor; if (grossLoss > 0) profitFactor = grossWin / grossLoss; else if (grossWin > 0) profitFactor = null; else profitFactor = 0d; ObjectNode bootstrapOptions = JSON.objectNode().put("iterations", 256).put("seed", seed); ObjectNode bootstrap = LegacyResearchV2.blockBootstrapExpectancy(ordered, bootstrapOptions); ObjectNode riskOptions = JSON.objectNode().put("initialEquity", initialEquity).put("seed", seed); ObjectNode risk = LegacyResearchV2.computeRiskDiagnostics(ordered, riskOptions); ObjectNode out = JSON.objectNode().put("candidate_id", candidateId).put("asset", asset).put("selected", false).put("completed_trades", ordered.size()).put("wins", wins).put("losses", losses).put("breakeven", values.size() - wins - losses); putNullableNumber(out, "win_rate", values.isEmpty() ? null : wins / (double) values.size()); putNullableNumber(out, "expectancy_r", mean); putNullableNumber(out, "profit_factor", profitFactor); out.put("total_return", totalPnl / initialEquity).put("turnover", turnover); putNullableNumber(out, "exposure", periodBars != null && periodBars > 0 ? Math.min(1, heldBars / periodBars) : null); out.put("exposure_unit", "fraction_of_declared_window").put("max_drawdown_pct", risk.path("equity").path("max_drawdown_pct").asDouble()); ObjectNode robust = JSON.objectNode(); robust.set("bootstrap_p20_expectancy_r", cloneNode(bootstrap.get("bootstrap_p20_expectancy_r"))); robust.put("effective_independent_episode_count", LegacyResearchV2.effectiveIndependentEpisodeCount(ordered)); robust.putNull("max_statistic_p_value"); out.set("robust_stats", robust); out.set("risk_diagnostics", risk); out.put("candidate_count", candidateCount); putNullableNumber(out, "search_adjusted_expectancy_r", mean == null ? null : LegacyResearchV2.searchAdjustedExpectancyHeuristic(mean, values.size(), candidateCount)); return out; }

    private static ObjectNode canonicalTrade(JsonNode raw, String candidateId, String asset, int index, JsonNode instrument) { ObjectNode trade = objectCopy(raw, "trade"); double risk = jsNumber(raw.get("risk_dollars")); String sourceId = bool(raw.get("trade_id")) ? text(raw.get("trade_id")) : asset + ":" + text(raw.get("signal_time")) + ":" + index; trade.put("source_trade_id", sourceId).put("trade_id", candidateId + ":" + asset.toLowerCase(Locale.ROOT) + ":" + sourceId).put("candidate_id", candidateId).put("asset", asset.toLowerCase(Locale.ROOT)); trade.set("instrument", instrument == null ? (present(raw.get("instrument")) ? cloneNode(raw.get("instrument")) : NullNode.instance) : cloneNode(instrument)); String event = bool(raw.get("event_id")) ? text(raw.get("event_id")) : bool(raw.get("episode_id")) ? text(raw.get("episode_id")) : asset + ":" + text(raw.get("signal_time")); String episode = bool(raw.get("episode_id")) ? text(raw.get("episode_id")) : bool(raw.get("event_id")) ? text(raw.get("event_id")) : event; trade.put("event_id", event).put("episode_id", episode); putNullableNumber(trade, "fee_r", Double.isFinite(jsNumber(raw.get("fee_r"))) && raw.has("fee_r") ? jsNumber(raw.get("fee_r")) : Double.isFinite(jsNumber(raw.get("fees"))) && raw.has("fees") && risk > 0 ? jsNumber(raw.get("fees")) / risk : null); putNullableNumber(trade, "slippage_r", Double.isFinite(jsNumber(raw.get("slippage_r"))) && raw.has("slippage_r") ? jsNumber(raw.get("slippage_r")) : Double.isFinite(jsNumber(raw.get("slippage_debit"))) && raw.has("slippage_debit") && risk > 0 ? jsNumber(raw.get("slippage_debit")) / risk : null); putNullableNumber(trade, "funding_debit_r", Double.isFinite(jsNumber(raw.get("funding_debit_r"))) && raw.has("funding_debit_r") ? jsNumber(raw.get("funding_debit_r")) : Double.isFinite(jsNumber(raw.get("funding_pnl"))) && raw.has("funding_pnl") && risk > 0 ? Math.max(0, -jsNumber(raw.get("funding_pnl"))) / risk : null); return trade; }

    private static ArrayNode sortedTrades(JsonNode trades) { List<JsonNode> ordered = new ArrayList<>(rows(trades)); ordered.sort(Comparator.comparingLong((JsonNode row) -> time(row.get("entry_time"))).thenComparing(row -> text(row.get("trade_id")))); return arrayOf(ordered); }

    private static void completeMissingRows(Evaluation state) { for (JsonNode candidate : state.candidates) for (String asset : state.assets) { String id = text(candidate.get("candidate_id")); if (rows(state.metricRows).stream().anyMatch(row -> id.equals(text(row.get("candidate_id"))) && asset.equals(text(row.get("asset"))))) continue; ObjectNode sourceFailure = state.assetFailures.getOrDefault(id + "|" + asset, state.candidateFailures.getOrDefault(id, failure("NO_RESULT", "candidate produced no authoritative result"))); state.metricRows.add(metricRow(id, asset, false, "REJECTED", state.adapter, authoritativeMetric(id, asset, JSON.arrayNode(), state.runtimeK, initialEquity(state.normalized.get(id), state.experiment), Math.max(1, state.windowRows.get(asset).size()), state.seed), sourceFailure)); } }
    private static void markSelections(Evaluation state, Map<String, String> frozenByAsset) { if (!frozenByAsset.isEmpty()) frozenByAsset.forEach((asset, id) -> state.selectedByAsset.put(asset, new LinkedHashSet<>(List.of(id)))); }

    private static String objectiveName(JsonNode objective) { String raw = objective != null && objective.isTextual() ? text(objective) : optionText(objective, "metric", optionText(objective, "field", optionText(objective, "name", ""))); return switch (raw) { case "expectancy", "expectancy_r" -> "expectancy_r"; case "profit_factor" -> "profit_factor"; case "total_return" -> "total_return"; case "bootstrap_p20_expectancy_r", "expectancy_bootstrap_20" -> "expectancy_bootstrap_20"; case "search_adjusted_expectancy_r" -> "search_adjusted_expectancy_r"; default -> raw; }; }
    private static Double metricField(JsonNode report, String field) { if (Set.of("candidate_id", "id").contains(field)) return null; if (Set.of("trades", "completed_trades").contains(field)) return numberOr(report.path("metrics").get("completed_trades"), 0); if ("bootstrap_p20_expectancy_r".equals(field)) field = "expectancy_bootstrap_20"; JsonNode metrics = report.path("metrics").isObject() ? report.get("metrics") : report; return nullableNumber(metrics.get(field)); }
    private static boolean gatePass(JsonNode report, JsonNode gate) { if (gate == null || !gate.isObject() || gate.isEmpty()) return false; JsonNode metrics = report.path("metrics").isObject() ? report.get("metrics") : JSON.objectNode(); JsonNode minTrades = firstDefined(gate, "minimum_completed_trades", "min_completed_trades", "minimum_trades", "completed_trades"), minExpectancy = firstDefined(gate, "minimum_expectancy_r", "min_expectancy_r", "expectancy_r"), minPf = firstDefined(gate, "minimum_profit_factor", "min_profit_factor", "profit_factor"), maxDd = firstDefined(gate, "maximum_drawdown_pct", "max_drawdown_pct", "max_drawdown"); if (minTrades != null && numberOr(metrics.get("completed_trades"), 0) < jsNumber(minTrades)) return false; if (minExpectancy != null && !(jsNumber(metrics.get("expectancy_r")) >= jsNumber(minExpectancy))) return false; if (minPf != null && !(jsNumber(metrics.get("profit_factor")) >= jsNumber(minPf) || metrics.path("profit_factor_unbounded").asBoolean(false))) return false; double dd = metrics.has("max_drawdown") ? jsNumber(metrics.get("max_drawdown")) : jsNumber(metrics.get("max_drawdown_pct")) / 100; if (maxDd != null && dd > jsNumber(maxDd)) return false; return gate.path("require_finite").isBoolean() && !gate.path("require_finite").asBoolean() || nullableNumber(metrics.get("expectancy_r")) != null; }
    private static String chooseWinner(List<JsonNode> reports, JsonNode chronology, JsonNode gate) { String objective = objectiveName(chronology.get("selection_objective")); if (!Set.of("expectancy_r", "profit_factor", "total_return", "expectancy_bootstrap_20", "search_adjusted_expectancy_r").contains(objective)) throw new IllegalArgumentException("selection_objective is unsupported for the registered executor: " + (objective.isEmpty() ? "missing" : objective)); List<JsonNode> eligible = reports.stream().filter(report -> gatePass(report, gate) && metricField(report, objective) != null).toList(); if (eligible.isEmpty()) return null; int direction = "min".equals(lower(chronology.path("selection_objective").get("direction"))) ? -1 : 1; List<JsonNode> sorted = new ArrayList<>(eligible); sorted.sort((left, right) -> { double lv = metricField(left, objective), rv = metricField(right, objective); if (lv != rv) return direction * Double.compare(rv, lv); for (JsonNode raw : rows(chronology.get("tie_breaker"))) { String field = raw.isTextual() ? text(raw) : optionText(raw, "field", text(raw.get("metric"))); if (field.isEmpty()) throw new IllegalArgumentException("tie_breaker contains an invalid field"); int sign = raw.isObject() && "min".equals(lower(raw.get("direction"))) ? -1 : 1; if (Set.of("candidate_id", "id").contains(field)) { String li = optionText(left, "candidate_id", text(left.path("candidate").get("id"))), ri = optionText(right, "candidate_id", text(right.path("candidate").get("id"))); int comparison = li.compareTo(ri); if (comparison != 0) return sign * comparison; } else { Double l = metricField(left, field), r = metricField(right, field); if (l == null || r == null) throw new IllegalArgumentException("tie_breaker metric " + field + " is unavailable for train selection"); if (!l.equals(r)) return sign * Double.compare(r, l); } } String id = optionText(left, "candidate_id", text(left.path("candidate").get("id"))); throw new IllegalArgumentException("ambiguous train selection tie for " + id + "; declare a deterministic tie_breaker"); }); return optionText(sorted.get(0), "candidate_id", text(sorted.get(0).path("candidate").get("id"))); }

    private static void verifyFoldArtifact(JsonNode fold, int index, JsonNode experiment, JsonNode candidateSet, JsonNode manifest) { JsonNode artifact = fold.get("artifact"); if (artifact == null || !artifact.isObject()) throw new IllegalArgumentException("fold " + index + " artifact content is required"); if (!text(fold.get("artifact_sha256")).matches("^[a-f0-9]{64}$") || !text(fold.get("artifact_sha256")).equals(LegacyResearchV2.hash(artifact))) throw new IllegalArgumentException("fold " + index + " artifact hash mismatch"); if (!bool(artifact.get("fold_id"))) throw new IllegalArgumentException("fold " + index + " artifact fold_id is required"); JsonNode train = firstDefined(fold, "train", "training"), test = firstDefined(fold, "test", "oos", "test_window"), artifactTrain = firstDefined(artifact, "train", "training", "train_window"), artifactTest = firstDefined(artifact, "test", "oos", "test_window"); if (artifactTrain == null || artifactTest == null) throw new IllegalArgumentException("fold " + index + " artifact must bind train and test windows"); if (time(artifactTrain.get("start")) != time(train.get("start")) || time(artifactTrain.get("end")) != time(train.get("end")) || time(artifactTest.get("start")) != time(test.get("start")) || time(artifactTest.get("end")) != time(test.get("end"))) throw new IllegalArgumentException("fold " + index + " artifact window binding mismatch"); Map<String, String> bindings = Map.of("experiment_sha256", prospectiveBindingHash(experiment), "candidate_set_sha256", LegacyResearchV2.hash(candidateSet), "data_manifest_sha256", optionText(manifest, "content_sha256", LegacyResearchV2.ownHash(manifest))); bindings.forEach((field, expected) -> { if (!artifact.has(field) || !expected.equals(text(artifact.get(field)))) throw new IllegalArgumentException("fold " + index + " artifact " + field + " binding mismatch"); }); }
    private static ObjectNode windowNode(long start, long end) { return JSON.objectNode().put("start", start).put("end", end); }

    private static ObjectNode maxStatistic(Map<String, List<String>> groups, ArrayNode trades, JsonNode chronology, int runtimeK) { ArrayNode candidates = JSON.arrayNode(); for (var entry : groups.entrySet()) { List<String> ids = entry.getValue().stream().sorted().toList(); String representative = ids.stream().filter(id -> rows(trades).stream().anyMatch(trade -> id.equals(text(trade.get("candidate_id"))))).findFirst().orElse(ids.isEmpty() ? "" : ids.get(0)); ObjectNode row = JSON.objectNode().put("candidate_id", representative).put("behavior_sha256", entry.getKey()); ArrayNode returns = JSON.arrayNode(); for (JsonNode trade : trades) if (representative.equals(text(trade.get("candidate_id")))) returns.add(cloneNode(trade)); row.set("rows", returns); candidates.add(row); } ObjectNode options = JSON.objectNode().put("iterations", 256).put("seed", jsNumber(chronology.path("seeds").get(0))).put("blockSize", numberOr(chronology.get("bootstrap_block_size"), 1)); return LegacyResearchV2.candidateSetMaxStatisticPValue(candidates, options); }
    private static ObjectNode noSelectedStress(JsonNode experiment) { ObjectNode result = JSON.objectNode().put("suite_sha256", LegacyResearchV2.hash(experiment.path("acceptance").get("stress"))).put("pass", false); result.set("scenarios", JSON.arrayNode()); ObjectNode failure = JSON.objectNode().put("code", "NO_SELECTED_TRADES").put("scope", "PORTFOLIO"); result.set("failures", JSON.arrayNode().add(failure)); return result; }
    private static void validateProspectiveTrades(String phase, JsonNode chronology, ArrayNode trades) { if (!"PROSPECTIVE_LIVE".equals(phase)) return; long start = time(firstTruthy(chronology, "frozen_start_time", "prospective_start")), end = time(chronology.path("monitoring_window").get("end")); for (JsonNode trade : trades) { long signal = time(trade.get("signal_time")), exit = time(trade.get("exit_time")); if (signal < start || exit < start || signal > end || exit > end) throw new IllegalArgumentException("prospective trade " + text(trade.get("trade_id")) + " falls outside frozen monitoring window"); } }
    private static ArrayNode portfolioMarks(ArrayNode decoded, List<String> assets, Map<String, JsonNode> identities) { ArrayNode marks = JSON.arrayNode(); for (JsonNode row : decoded) { String asset = lower(row.get("asset")); if (!assets.contains(asset) || !Double.isFinite(jsNumber(row.get("close")))) continue; JsonNode declared = identities.getOrDefault(asset, JSON.objectNode()); String symbol = optionText(row, "symbol", optionText(row, "instrument_id", optionText(row, "instrument_symbol", optionText(declared, "symbol", text(row.get("asset")))))); ObjectNode mark = JSON.objectNode().put("asset", asset).put("instrument_id", optionText(row, "instrument_id", symbol)).put("symbol", symbol).put("time", jsNumber(row.get("time"))).put("price", jsNumber(row.get("close"))); JsonNode venue = firstTruthy(row, "venue"); if (venue == null) venue = declared.get("venue"); if (venue == null) mark.putNull("venue"); else mark.set("venue", cloneNode(venue)); marks.add(mark); } return marks; }
    private static ObjectNode simulatePortfolio(JsonNode experiment, JsonNode chronology, ArrayNode selectedTrades, ArrayNode marks) {
        ArrayNode signals = JSON.arrayNode();
        for (JsonNode trade : selectedTrades) {
            ObjectNode signal = objectCopy(trade, "selected trade");
            signal.put("signal_id", text(trade.get("trade_id")));
            double quantity = jsNumber(trade.get("quantity"));
            double entry = jsNumber(trade.get("entry_price"));
            double notional = jsNumber(trade.get("notional"));
            if (notional == 0) notional = Math.abs(quantity * entry);
            if (quantity == 0) quantity = notional / entry;
            putNullableNumber(signal, "notional", Double.isFinite(notional) ? notional : null);
            putNullableNumber(signal, "quantity", Double.isFinite(quantity) ? quantity : null);
            if (trade.has("instrument")) signal.set("instrument", cloneNode(trade.get("instrument")));
            if (trade.has("funding_settlements")) signal.set("funding_settlements", cloneNode(trade.get("funding_settlements")));
            signals.add(signal);
        }
        ObjectNode policy = experiment.path("portfolio_policy").isObject()
                ? objectCopy(experiment.get("portfolio_policy"), "portfolio policy")
                : JSON.objectNode();
        policy.put("authoritative", true);
        double initial = bool(experiment.path("portfolio_policy").get("initial_equity"))
                ? jsNumber(experiment.path("portfolio_policy").get("initial_equity"))
                : bool(experiment.get("initial_equity")) ? jsNumber(experiment.get("initial_equity")) : 100_000;
        policy.put("initial_equity", initial);
        if (!policy.has("max_mark_gap_ms") && chronology.has("bar_duration_ms")) policy.set("max_mark_gap_ms", cloneNode(chronology.get("bar_duration_ms")));
        policy.set("marks", marks);
        policy.set("acceptance", cloneNode(experiment.path("acceptance").get("portfolio")));
        try {
            Class<?> type = Class.forName("com.tradinganalytics.research.v5.StrategyPortfolioV5");
            Method method = type.getMethod("simulateCryptoPortfolio", JsonNode.class, JsonNode.class);
            return (ObjectNode) method.invoke(null, signals, policy);
        } catch (InvocationTargetException error) {
            Throwable cause = error.getCause() == null ? error : error.getCause();
            return portfolioFailure(experiment, message(cause));
        } catch (ClassNotFoundException | NoSuchMethodException | IllegalAccessException | ClassCastException error) {
            return portfolioFailure(experiment, message(error));
        }
    }
    private static ObjectNode portfolioFailure(JsonNode experiment, String reason) { ObjectNode result = JSON.objectNode().put("pass", false).put("activation", "RESEARCH_ONLY"); ObjectNode failure = JSON.objectNode().put("code", "PORTFOLIO_REJECTED").put("scope", "PORTFOLIO").put("reason", reason); result.set("failures", JSON.arrayNode().add(failure)); result.put("rejection_reason", reason).put("acceptance_contract_sha256", LegacyResearchV2.hash(experiment.path("acceptance").get("portfolio"))); return result; }
    private static String portfolioSourceHash(JsonNode experiment, JsonNode chronology, String selectedTradesHash, ArrayNode marks) { ObjectNode source = JSON.objectNode().put("selected_trades_sha256", selectedTradesHash).put("marks_sha256", LegacyResearchV2.hash(marks)).put("initial_equity", bool(experiment.path("portfolio_policy").get("initial_equity")) ? jsNumber(experiment.path("portfolio_policy").get("initial_equity")) : bool(experiment.get("initial_equity")) ? jsNumber(experiment.get("initial_equity")) : 100_000); source.set("policy", experiment.path("portfolio_policy").isObject() ? cloneNode(experiment.get("portfolio_policy")) : JSON.objectNode()); source.set("acceptance", cloneNode(experiment.path("acceptance").get("portfolio"))); return LegacyResearchV2.hash(source); }

    private static ArrayNode decisions(Evaluation state, Map<String, ObjectNode> candidateFailures, Map<String, ObjectNode> assetFailures) { ArrayNode result = JSON.arrayNode(); for (String asset : state.assets) { List<String> selected = new ArrayList<>(state.selectedByAsset.getOrDefault(asset, Set.of())); selected.sort(String::compareTo); List<String> reasons = new ArrayList<>(); if (selected.isEmpty()) reasons.add("NO_TRAIN_SELECTED_CANDIDATE"); for (String id : selected) { ObjectNode failure = assetFailures.getOrDefault(id + "|" + asset, candidateFailures.get(id)); if (failure != null) reasons.add(text(failure.get("code"))); } ObjectNode row = JSON.objectNode().put("asset", asset); if (selected.size() == 1) row.put("candidate_id", selected.get(0)); else row.putNull("candidate_id"); row.set("candidate_ids", strings(selected)); row.put("status", reasons.isEmpty() ? "SHADOW" : "REJECTED"); row.set("reasons", strings(reasons.isEmpty() ? List.of("RESEARCH_EVIDENCE_ONLY") : reasons.stream().distinct().toList())); result.add(row); } return result; }
    private static String candidateTradeSetHash(ArrayNode metrics, ArrayNode trades) { ArrayNode rows = JSON.arrayNode(); for (JsonNode metric : metrics) { String candidate = text(metric.get("candidate_id")), asset = text(metric.get("asset")); ArrayNode scoped = JSON.arrayNode(); for (JsonNode trade : trades) if (candidate.equals(text(trade.get("candidate_id"))) && asset.equals(text(trade.get("asset")))) scoped.add(cloneNode(trade)); rows.add(JSON.objectNode().put("candidate_id", candidate).put("asset", asset).put("trade_hash", LegacyResearchV2.hash(scoped))); } return LegacyResearchV2.hash(rows); }
    private static ArrayNode failures(Map<String, ObjectNode> candidateFailures, Map<String, ObjectNode> assetFailures, List<String> assets) { ArrayNode result = JSON.arrayNode(); candidateFailures.forEach((candidate, failure) -> assets.forEach(asset -> { ObjectNode row = JSON.objectNode().put("candidate_id", candidate).put("asset", asset).put("scope", "CANDIDATE_ASSET"); row.setAll(failure); result.add(row); })); assetFailures.forEach((key, failure) -> { String[] parts = key.split("\\|", 2); ObjectNode row = JSON.objectNode().put("candidate_id", parts[0]).put("asset", parts.length > 1 ? parts[1] : "").put("scope", "CANDIDATE_ASSET"); row.setAll(failure); result.add(row); }); return result; }
    private static void putPathOrNull(ObjectNode target, String field, JsonNode value) { if (!bool(value)) target.putNull(field); else target.put(field, Path.of(text(value)).toAbsolutePath().normalize().toString()); }
}
