package com.tradinganalytics.research.legacy;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.NullNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.tradinganalytics.contracts.schema.ResearchSchemaRegistry;
import com.tradinganalytics.infrastructure.security.PathConfinement;
import com.tradinganalytics.infrastructure.security.SecureFileOperations;
import com.tradinganalytics.research.swing.SwingEngine;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeFormatterBuilder;
import java.time.temporal.ChronoField;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

import static com.tradinganalytics.research.legacy.LegacyResearchSupport.*;

/** Java compatibility implementation of {@code strategy-research-lib.mjs}. */
public final class LegacyResearchV1 {
    public static final String REGISTRY_SCHEMA = "strategy-research-index/1";
    public static final String DEFINITION_SCHEMA = "strategy-definition/1";
    public static final String EXPERIMENT_SCHEMA = "strategy-experiment/1";
    public static final String CANDIDATE_SET_SCHEMA = "strategy-candidate-set/1";
    public static final String RUN_SCHEMA = "strategy-run/1";
    public static final List<String> EVIDENCE_PHASES = List.of("DEVELOPMENT", "WALK_FORWARD_OOS", "EXPOSED_CONFIRMATION", "SEALED_CONFIRMATION", "PROSPECTIVE_LIVE");
    public static final List<String> DECISION_STATUSES = List.of("REJECTED", "SHADOW", "CANDIDATE_REVIEW", "ACTIVE");
    public static final long MAX_TRACKED_ARTIFACT_BYTES = 10L * 1024 * 1024;
    public static final String CANDIDATE_SET_V2_SCHEMA = LegacyResearchV2.CANDIDATE_SET_V2_SCHEMA;
    public static final String DEFINITION_V2_SCHEMA = LegacyResearchV2.DEFINITION_V2_SCHEMA;
    public static final String EXPERIMENT_V2_SCHEMA = LegacyResearchV2.EXPERIMENT_V2_SCHEMA;
    public static final String PRECOMMIT_SCHEMA = LegacyResearchV2.PRECOMMIT_SCHEMA;
    public static final String RUN_V2_SCHEMA = LegacyResearchV2.RUN_V2_SCHEMA;
    private static final DateTimeFormatter JS_ISO = new DateTimeFormatterBuilder().appendInstant(3).toFormatter().withZone(ZoneOffset.UTC);

    public record LegacySource(String path, List<String> assets, String evidencePhase) {}
    public static final List<LegacySource> LEGACY_SOURCES = List.of(
            source("market-context-run.json", "btc", "eth", "WALK_FORWARD_OOS"), source("direction-router-search-v1.json", "btc", "eth", "DEVELOPMENT"), source("direction-router-search-v2.json", "btc", "eth", "DEVELOPMENT"), source("trend-down-search-v1.json", "btc", "eth", "DEVELOPMENT"), source("online-selector-search-v1.json", "btc", "eth", "DEVELOPMENT"), source("size-balance-search-v1.json", "btc", "eth", "DEVELOPMENT"), source("structural-router-search-v3.json", "btc", "eth", "DEVELOPMENT"), source("percentile-atr-search-v1.json", "btc", "eth", "DEVELOPMENT"), source("percentile-atr-search-v2.json", "btc", "eth", "DEVELOPMENT"),
            new LegacySource("refinement-search/results.json", List.of("btc", "eth", "sol"), "EXPOSED_CONFIRMATION"), new LegacySource("universal-v4-search/results.json", List.of("btc", "eth", "sol", "bnb", "xrp"), "EXPOSED_CONFIRMATION"), new LegacySource("sol-cross-asset-validation.json", List.of("sol"), "EXPOSED_CONFIRMATION"), new LegacySource("bnb-cross-asset-validation-v2.json", List.of("bnb"), "EXPOSED_CONFIRMATION"), new LegacySource("xrp-cross-asset-validation-v1.json", List.of("xrp"), "EXPOSED_CONFIRMATION"), new LegacySource("ada-structural-router-validation-v1.json", List.of("ada"), "SEALED_CONFIRMATION"), new LegacySource("link-balanced-router-validation-v1.json", List.of("link"), "SEALED_CONFIRMATION"), new LegacySource("aave-percentile-atr-router-validation-v1.json", List.of("aave"), "SEALED_CONFIRMATION"));

    private LegacyResearchV1() {}

    public static String stable(JsonNode value) { return LegacyResearchSupport.stable(value); }
    public static String hash(JsonNode value) { return LegacyResearchSupport.hash(value); }
    public static String hash(String value) { return LegacyResearchSupport.hash(value); }
    public static JsonNode readJSON(Path path) { return readJson(path); }
    public static JsonNode readJSON(String path) { return readJSON(Path.of(path)); }
    public static byte[] jsonBytes(JsonNode value) { return LegacyResearchSupport.jsonBytes(value); }
    public static byte[] jsonlBytes(JsonNode value) { return LegacyResearchSupport.jsonlBytes(value); }
    public static ArrayNode readJSONL(Path path) { return readJsonl(path); }
    public static ArrayNode readJSONL(String path) { return readJSONL(Path.of(path)); }

    public static boolean validateFeatureContract(JsonNode contract) {
        object(contract, "feature_contract"); if (!contract.path("series").isArray() || contract.path("series").isEmpty()) throw new IllegalArgumentException("feature_contract.series must be non-empty"); if (!contract.path("inputs").isArray() || contract.path("inputs").isEmpty()) throw new IllegalArgumentException("feature_contract.inputs must be non-empty"); Set<String> seriesIds = new LinkedHashSet<>();
        for (JsonNode item : contract.get("series")) { object(item, "feature_contract.series[]"); requiredDefined(item, List.of("series_id", "asset", "timeframe", "point_in_time"), "feature_contract.series[]"); String id = text(item.get("series_id")); if (!seriesIds.add(id)) throw new IllegalArgumentException("duplicate feature series " + id); String status = text(item.path("point_in_time").get("status")); if (!List.of("VERIFIED", "PROXY_DISCLOSED", "UNKNOWN", "UNSAFE").contains(status)) throw new IllegalArgumentException("invalid PIT status for " + id); if ("VERIFIED".equals(status) && !item.path("point_in_time").path("completed_bar_only").asBoolean(false)) throw new IllegalArgumentException("VERIFIED series " + id + " must be completed-bar only"); }
        Set<String> inputIds = new LinkedHashSet<>(); for (JsonNode input : contract.get("inputs")) { object(input, "feature_contract.inputs[]"); requiredDefined(input, List.of("input_id", "field_path", "source", "transformation", "availability", "point_in_time", "minimum_coverage", "role"), "feature_contract.inputs[]"); String id = text(input.get("input_id")); if (!inputIds.add(id)) throw new IllegalArgumentException("duplicate feature input " + id); object(input.get("source"), "feature_contract.inputs." + id + ".source"); object(input.get("transformation"), "feature_contract.inputs." + id + ".transformation"); object(input.get("availability"), "feature_contract.inputs." + id + ".availability"); double coverage = jsNumber(input.get("minimum_coverage")); if (!(coverage >= 0 && coverage <= 1)) throw new IllegalArgumentException("invalid minimum coverage for " + id); if (!List.of("SETUP", "SCORE", "CONTEXT", "VETO", "COST", "OUTCOME_ONLY").contains(text(input.get("role")))) throw new IllegalArgumentException("invalid feature role for " + id); } return true;
    }

    public static boolean validateDefinition(JsonNode value) { return DEFINITION_V2_SCHEMA.equals(text(value == null ? null : value.get("schema"))) ? LegacyResearchV2.validateDefinitionV2(value) : validateDefinitionV1(value); }
    public static boolean validateExperiment(JsonNode value) { return EXPERIMENT_V2_SCHEMA.equals(text(value == null ? null : value.get("schema"))) ? LegacyResearchV2.validateExperimentV2(value) : validateExperimentV1(value); }
    public static boolean validateCandidateSet(JsonNode value) { return CANDIDATE_SET_V2_SCHEMA.equals(text(value == null ? null : value.get("schema"))) ? LegacyResearchV2.validateCandidateSetV2(value) : validateCandidateSetV1(value); }

    private static boolean validateDefinitionV1(JsonNode value) { object(value, "definition"); requiredDefined(value, List.of("schema", "strategy_id", "version", "created_at", "lineage", "candidate_template", "feature_contract", "evidence_policy"), "definition"); if (!DEFINITION_SCHEMA.equals(text(value.get("schema")))) throw new IllegalArgumentException("unsupported definition schema " + text(value.get("schema"))); safeId(value.get("strategy_id"), "strategy_id"); if (!text(value.get("version")).matches("^v[0-9]{3}$")) throw new IllegalArgumentException("definition.version must be vNNN"); object(value.get("lineage"), "definition.lineage"); requiredDefined(value.get("lineage"), List.of("parent_version", "change_summary"), "definition.lineage"); validateFeatureContract(value.get("feature_contract")); object(value.get("evidence_policy"), "evidence_policy"); if (value.path("evidence_policy").path("activation_allowed").asBoolean(true)) throw new IllegalArgumentException("research definitions must declare activation_allowed:false"); ObjectNode candidate = SwingEngine.normalizeCandidate(value.get("candidate_template")); if (candidate.path("max_concurrent").asInt() > 1) throw new IllegalArgumentException("max_concurrent > 1 requires an implemented portfolio concurrency model"); return true; }
    private static boolean validateExperimentV1(JsonNode value) { object(value, "experiment"); requiredDefined(value, List.of("schema", "experiment_id", "created_at", "definition", "evidence_phase", "required_assets", "grid", "candidate_set", "acceptance"), "experiment"); if (!EXPERIMENT_SCHEMA.equals(text(value.get("schema")))) throw new IllegalArgumentException("unsupported experiment schema " + text(value.get("schema"))); safeId(value.get("experiment_id"), "experiment_id"); if (!EVIDENCE_PHASES.contains(text(value.get("evidence_phase")))) throw new IllegalArgumentException("invalid evidence phase " + text(value.get("evidence_phase"))); if (!value.path("required_assets").isArray() || value.path("required_assets").isEmpty()) throw new IllegalArgumentException("experiment.required_assets must be non-empty"); object(value.get("definition"), "experiment.definition"); requiredDefined(value.get("definition"), List.of("path", "sha256"), "experiment.definition"); object(value.get("grid"), "experiment.grid"); object(value.get("candidate_set"), "experiment.candidate_set"); object(value.get("acceptance"), "experiment.acceptance"); return true; }
    private static boolean validateCandidateSetV1(JsonNode value) { object(value, "candidate_set"); requiredDefined(value, List.of("schema", "experiment_id", "declared_k", "effective_k", "declared_sha256", "effective_sha256", "per_series", "candidates"), "candidate_set"); if (!CANDIDATE_SET_SCHEMA.equals(text(value.get("schema")))) throw new IllegalArgumentException("unsupported candidate set schema " + text(value.get("schema"))); if (jsNumber(value.get("effective_k")) != value.path("candidates").size() || jsNumber(value.get("declared_k")) < jsNumber(value.get("effective_k"))) throw new IllegalArgumentException("candidate set K/count mismatch"); if (!hash(value.get("candidates")).equals(text(value.get("effective_sha256")))) throw new IllegalArgumentException("candidate set effective hash mismatch"); return true; }

    public static boolean validateRun(JsonNode value) { object(value, "run"); requiredDefined(value, List.of("schema", "run_id", "content_sha256", "evidence_phase", "experiment", "candidate_accounting", "artifacts", "decisions", "activation"), "run"); if (!RUN_SCHEMA.equals(text(value.get("schema")))) throw new IllegalArgumentException("unsupported run schema " + text(value.get("schema"))); if (!EVIDENCE_PHASES.contains(text(value.get("evidence_phase")))) throw new IllegalArgumentException("invalid evidence phase " + text(value.get("evidence_phase"))); if (value.path("activation").path("authorized").asBoolean(true)) throw new IllegalArgumentException("strategy research run cannot authorize activation"); List<JsonNode> decisions = new ArrayList<>(rows(value.path("decisions").get("per_asset"))); if (present(value.path("decisions").get("portfolio"))) decisions.add(value.path("decisions").get("portfolio")); for (JsonNode decision : decisions) if (!DECISION_STATUSES.contains(text(decision.get("status")))) throw new IllegalArgumentException("invalid decision status " + text(decision.get("status"))); ObjectNode payload = objectCopy(value, "run"); payload.remove(List.of("run_id", "content_sha256", "generated_at")); String expected = hash(payload); if (!expected.equals(text(value.get("content_sha256"))) || !expected.equals(text(value.get("run_id")))) throw new IllegalArgumentException("run content hash mismatch"); return true; }

    public static ArrayNode expandGrid(JsonNode template) { return expandGrid(template, JSON.objectNode()); }
    public static ArrayNode expandGrid(JsonNode template, JsonNode grid) { object(grid, "grid"); List<String> keys = new ArrayList<>(); grid.fieldNames().forEachRemaining(keys::add); keys.sort(String::compareTo); for (String key : keys) if (!grid.get(key).isArray() || grid.get(key).isEmpty()) throw new IllegalArgumentException("grid." + key + " must be a non-empty array"); List<ObjectNode> expanded = new ArrayList<>(); expanded.add(objectCopy(template, "template")); for (String key : keys) { List<ObjectNode> next = new ArrayList<>(); for (ObjectNode row : expanded) for (JsonNode value : grid.get(key)) { ObjectNode copy = row.deepCopy(); setPath(copy, key, value); next.add(copy); } expanded = next; } ArrayNode result = JSON.arrayNode(); for (int index = 0; index < expanded.size(); index++) { ObjectNode row = expanded.get(index); String sequence = String.format(Locale.ROOT, "%04d", index + 1), id; if (bool(row.get("id_template"))) id = text(row.get("id_template")).replace("{n}", sequence); else id = expanded.size() == 1 && bool(row.get("id")) ? text(row.get("id")) : optionText(row, "id", "candidate") + "-" + sequence; row.put("id", id); result.add(row); } return result; }

    public static ObjectNode accountCandidates(JsonNode candidates) { return accountCandidates(candidates, JSON.arrayNode()); }
    public static ObjectNode accountCandidates(JsonNode candidates, JsonNode series) { Map<String, String> ids = new LinkedHashMap<>(); Map<String, CandidateBehavior> behaviors = new LinkedHashMap<>(); ArrayNode declared = JSON.arrayNode(); for (JsonNode raw : rows(candidates)) { ObjectNode normalized = SwingEngine.normalizeCandidate(raw); ObjectNode effective = normalized.deepCopy(); effective.remove(List.of("id", "raw", "_state", "_impulse")); String behavior = hash(effective), id = text(normalized.get("id")); if (normalized.path("max_concurrent").asInt() > 1) throw new IllegalArgumentException("candidate " + id + " has max_concurrent > 1 without portfolio concurrency support"); if (ids.containsKey(id) && !ids.get(id).equals(behavior)) throw new IllegalArgumentException("candidate id conflict: " + id); ids.put(id, behavior); declared.add(JSON.objectNode().put("id", id).put("behavior_sha256", behavior)); ObjectNode rawWithId = objectCopy(raw, "candidate"); rawWithId.put("id", id); behaviors.putIfAbsent(behavior, new CandidateBehavior(rawWithId, normalized)); }
        List<String> behaviorKeys = new ArrayList<>(behaviors.keySet()); behaviorKeys.sort(String::compareTo); ArrayNode perSeries = JSON.arrayNode(); for (JsonNode item : rows(series)) { List<String> applicable = new ArrayList<>(); for (String behavior : behaviorKeys) { JsonNode candidate = behaviors.get(behavior).normalized(); if ((!candidate.path("assets").isArray() || candidate.path("assets").isEmpty() || containsText(candidate.get("assets"), text(item.get("asset")))) && (!candidate.path("timeframes").isArray() || candidate.path("timeframes").isEmpty() || containsText(candidate.get("timeframes"), text(item.get("timeframe")))) && (!bool(item.get("framework")) || text(candidate.get("framework")).equals(text(item.get("framework")))) && (!bool(item.get("channel")) || text(candidate.get("channel")).equals(text(item.get("channel"))))) applicable.add(behavior); } applicable.sort(String::compareTo); ObjectNode row = JSON.objectNode().put("series_id", text(item.get("series_id"))).put("declared_k", declared.size()).put("effective_k", new LinkedHashSet<>(applicable).size()).put("effective_behavior_sha256", hash(strings(applicable))); perSeries.add(row); }
        ArrayNode canonical = JSON.arrayNode(); for (String behavior : behaviorKeys) { CandidateBehavior value = behaviors.get(behavior); canonical.add(JSON.objectNode().put("candidate_id", text(value.candidate().get("id"))).put("behavior_sha256", behavior).set("definition", value.candidate())); } ObjectNode result = JSON.objectNode().put("declared_k", declared.size()).put("effective_k", canonical.size()).put("declared_sha256", hash(declared)).put("effective_sha256", hash(canonical)); result.set("per_series", perSeries); result.set("candidates", canonical); return result; }
    private record CandidateBehavior(ObjectNode candidate, ObjectNode normalized) {}

    public static ObjectNode buildCandidateSet(JsonNode experiment, JsonNode definition) { ObjectNode result = JSON.objectNode().put("schema", CANDIDATE_SET_SCHEMA).put("experiment_id", text(experiment.get("experiment_id"))); ObjectNode accounting = accountCandidates(expandGrid(definition.get("candidate_template"), experiment.get("grid")), definition.path("feature_contract").get("series")); result.setAll(accounting); return result; }

    public static ObjectNode compactMetrics(JsonNode metrics) { ObjectNode out = JSON.objectNode(); metric(out, "attempted_trades", metrics, "attempted_trades", "attempted"); metric(out, "completed_trades", metrics, "completed_trades", "trades"); metric(out, "wins", metrics, "wins"); metric(out, "losses", metrics, "losses"); metric(out, "expectancy_r", metrics, "expectancy_r", "average_r", "mean_r"); metric(out, "search_adjusted_expectancy_r", metrics, "search_adjusted_expectancy_r"); metric(out, "profit_factor", metrics, "profit_factor"); metric(out, "win_rate", metrics, "win_rate"); metric(out, "return_pct", metrics, "return_pct", "net_return_pct"); metric(out, "max_drawdown_pct", metrics, "max_drawdown_pct"); metric(out, "bootstrap_p20_expectancy_r", metrics, "bootstrap_p20_expectancy_r", "expectancy_bootstrap_p20"); metric(out, "positive_folds", metrics, "positive_folds"); return out; }

    public static ObjectNode makeRunBundle(JsonNode options) { JsonNode experiment = options.get("experiment"), definition = options.get("definition"), candidateSet = options.get("candidateSet"); validateExperiment(experiment); validateDefinition(definition); validateCandidateSet(candidateSet); ArrayNode metricRows = canonicalRows(rows(options.get("metrics"))), tradeRows = JSON.arrayNode(); for (JsonNode trade : rows(options.get("trades"))) tradeRows.add(pick(trade, "trade_id", "candidate_id", "series_id", "asset", "direction", "setup_family", "signal_time", "entry_time", "entry_price", "exit_time", "exit_price", "hold_bars", "net_r", "net_pnl", "exit_reason", "regime")); tradeRows = canonicalRows(rows(tradeRows)); ArrayNode candidateRows = canonicalRows(rows(candidateSet.get("candidates"))); Set<String> assetsSet = new LinkedHashSet<>(); for (JsonNode asset : rows(experiment.get("required_assets"))) assetsSet.add(lower(asset)); for (JsonNode metric : metricRows) if (bool(metric.get("asset"))) assetsSet.add(lower(metric.get("asset"))); List<String> assets = new ArrayList<>(assetsSet); assets.sort(String::compareTo);
        ArrayNode perAsset = JSON.arrayNode(); for (String asset : assets) { List<JsonNode> matches = rows(metricRows).stream().filter(row -> asset.equals(text(row.get("asset")))).toList(); JsonNode preferred = matches.stream().filter(row -> row.path("selected").asBoolean(false)).findFirst().orElse(matches.isEmpty() ? null : matches.get(0)); ObjectNode status = statusFor(preferred == null ? null : preferred.get("metrics"), text(experiment.get("evidence_phase")), pitSafe(definition, asset), experiment.get("acceptance")); status.put("asset", asset); if (preferred == null || !bool(preferred.get("candidate_id"))) status.putNull("selected_candidate_id"); else status.set("selected_candidate_id", cloneNode(preferred.get("candidate_id"))); perAsset.add(status); }
        JsonNode portfolioMetric = rows(metricRows).stream().filter(row -> "PORTFOLIO".equals(text(row.get("scope")))).findFirst().orElse(null); ObjectNode portfolio = statusFor(portfolioMetric == null ? null : portfolioMetric.get("metrics"), text(experiment.get("evidence_phase")), assets.stream().allMatch(asset -> pitSafe(definition, asset)), experiment.get("acceptance")); if (rows(perAsset).stream().anyMatch(row -> !"CANDIDATE_REVIEW".equals(text(row.get("status")))) && "CANDIDATE_REVIEW".equals(text(portfolio.get("status")))) { List<String> reasons = new ArrayList<>(); for (JsonNode reason : rows(portfolio.get("reasons"))) reasons.add(text(reason)); reasons.add("ALL_ASSETS_MUST_PASS_INDEPENDENTLY"); portfolio.set("reasons", strings(reasons)); }
        ObjectNode artifacts = JSON.objectNode(); artifacts.set("candidates", artifact("candidates.jsonl", candidateRows)); artifacts.set("metrics", artifact("metrics.jsonl", metricRows)); artifacts.set("trades", artifact("trades.jsonl", tradeRows)); ObjectNode payload = JSON.objectNode().put("schema", RUN_SCHEMA).put("evidence_phase", text(experiment.get("evidence_phase"))); ObjectNode experimentRef = JSON.objectNode().put("experiment_id", text(experiment.get("experiment_id"))).put("sha256", hash(experiment)).put("definition_sha256", hash(definition)).put("candidate_set_sha256", hash(candidateSet)); payload.set("experiment", experimentRef); JsonNode engine = options.get("engineResult"); if (!present(engine)) payload.putNull("engine"); else { ObjectNode engineRef = JSON.objectNode(); engineRef.set("schema", present(engine.get("engine")) ? cloneNode(engine.get("engine")) : NullNode.instance); engineRef.set("run_sha256", present(engine.get("run_sha256")) ? cloneNode(engine.get("run_sha256")) : NullNode.instance); engineRef.set("feature_store_sha256", present(engine.get("feature_store_sha256")) ? cloneNode(engine.get("feature_store_sha256")) : NullNode.instance); payload.set("engine", engineRef); } payload.set("candidate_accounting", pick(candidateSet, "declared_k", "effective_k", "declared_sha256", "effective_sha256", "per_series")); payload.set("artifacts", artifacts); ObjectNode decisions = JSON.objectNode(); decisions.set("per_asset", perAsset); decisions.set("portfolio", portfolio); payload.set("decisions", decisions); payload.set("activation", JSON.objectNode().put("authorized", false).put("status", "SHADOW").put("reason", "A research record cannot authorize trades; activation requires a separate governed review.")); payload.set("legacy", present(options.get("legacy")) ? cloneNode(options.get("legacy")) : NullNode.instance); String content = hash(payload); ObjectNode run = payload.deepCopy(); run.set("generated_at", present(options.get("generatedAt")) ? cloneNode(options.get("generatedAt")) : NullNode.instance); run.put("run_id", content).put("content_sha256", content); ObjectNode result = JSON.objectNode(); result.set("run", run); result.set("candidates", candidateRows); result.set("metrics", metricRows); result.set("trades", tradeRows); return result; }

    public static ObjectNode runExperiment(JsonNode experiment, JsonNode definition, JsonNode featureStore) { return runExperiment(experiment, definition, featureStore, Clock.systemUTC()); }
    public static ObjectNode runExperiment(JsonNode experiment, JsonNode definition, JsonNode featureStore, Clock clock) { if (!hash(definition).equals(text(experiment.path("definition").get("sha256")))) throw new IllegalArgumentException("definition hash mismatch"); ObjectNode candidateSet = buildCandidateSet(experiment, definition); ArrayNode candidateDefinitions = JSON.arrayNode(); for (JsonNode candidate : candidateSet.get("candidates")) candidateDefinitions.add(cloneNode(candidate.get("definition"))); ObjectNode engineOptions = experiment.path("engine_options").isObject() ? objectCopy(experiment.get("engine_options"), "engine_options") : JSON.objectNode(); engineOptions.put("candidate_count", candidateSet.path("effective_k").asInt()); engineOptions.set("retain_candidate_ids", present(experiment.get("finalist_candidate_ids")) ? cloneNode(experiment.get("finalist_candidate_ids")) : JSON.arrayNode()); ObjectNode result = SwingEngine.runResearch(SwingEngine.decodeFeatureStore(featureStore), candidateDefinitions, engineOptions, clock); ArrayNode reports = JSON.arrayNode(); reports.addAll((ArrayNode) result.path("leaderboard")); reports.addAll((ArrayNode) result.path("aggregate")); ArrayNode metrics = JSON.arrayNode(); for (JsonNode report : reports) { boolean asset = bool(report.get("series")); String series = text(report.get("series")); ObjectNode row = JSON.objectNode().put("scope", asset ? "ASSET" : "PORTFOLIO"); if (asset) row.put("series_id", series).put("asset", series.split("\\|", 2)[0]); else row.putNull("series_id").putNull("asset"); if (bool(report.path("candidate").get("id"))) row.set("candidate_id", cloneNode(report.path("candidate").get("id"))); else row.putNull("candidate_id"); row.put("selected", containsText(experiment.get("finalist_candidate_ids"), text(report.path("candidate").get("id")))); row.set("metrics", compactMetrics(report.get("metrics"))); metrics.add(row); } ObjectNode options = JSON.objectNode(); options.set("experiment", cloneNode(experiment)); options.set("definition", cloneNode(definition)); options.set("candidateSet", candidateSet); options.set("engineResult", result); options.set("metrics", metrics); options.set("trades", cloneNode(result.path("retained_trades"))); options.put("generatedAt", JS_ISO.format(clock.instant())); return makeRunBundle(options); }

    public static void writeImmutable(Path path, JsonNode value) { writeImmutable(path, value, false); }
    public static void writeImmutable(Path path, JsonNode value, boolean jsonl) { byte[] bytes = jsonl ? jsonlBytes(value) : jsonBytes(value); if (bytes.length > MAX_TRACKED_ARTIFACT_BYTES) throw new IllegalArgumentException("artifact exceeds 10MiB: " + path); if (Files.exists(path, LinkOption.NOFOLLOW_LINKS)) throw new IllegalArgumentException("overwrite refused: " + path); writeExclusive(path, bytes); }
    public static Path writeRunBundle(Path root, JsonNode bundle) { JsonNode run = bundle.get("run"); validateRun(run); Path runsRoot = root.toAbsolutePath().normalize().resolve("runs"); createRealDirectories(root.toAbsolutePath().normalize(), runsRoot); Path runRoot = runsRoot.resolve(text(run.get("run_id"))); if (Files.exists(runRoot, LinkOption.NOFOLLOW_LINKS)) throw new IllegalArgumentException("overwrite refused: " + runRoot); createRealDirectories(runsRoot, runRoot); writeImmutable(runRoot.resolve("candidates.jsonl"), bundle.get("candidates"), true); writeImmutable(runRoot.resolve("metrics.jsonl"), bundle.get("metrics"), true); writeImmutable(runRoot.resolve("trades.jsonl"), bundle.get("trades"), true); writeImmutable(runRoot.resolve("run.json"), run); return runRoot; }

    public static ObjectNode validateRunDirectory(Path runRoot) { ObjectNode run = objectCopy(readJSON(runRoot.resolve("run.json")), "run"); validateRunDirectoryValue(runRoot, run); return run; }
    private static void validateRunDirectoryValue(Path runRoot, JsonNode run) { validateRun(run); if (!runRoot.getFileName().toString().equals(text(run.get("run_id")))) throw new IllegalArgumentException("run directory name does not match run_id"); var fields = run.path("artifacts").fields(); while (fields.hasNext()) { JsonNode artifact = fields.next().getValue(); String relative = text(artifact.get("path")); String safe = PathConfinement.repositoryRelativePath(relative, "run artifact"); Path path = runRoot.toAbsolutePath().normalize().resolve(safe).normalize(); if (!path.startsWith(runRoot.toAbsolutePath().normalize()) || !Files.exists(path, LinkOption.NOFOLLOW_LINKS)) throw new IllegalArgumentException("missing run artifact " + relative); byte[] bytes = PathConfinement.readSinglyLinkedFile(path, "run artifact"); if (!LegacyResearchSupport.hash(bytes).equals(text(artifact.get("sha256")))) throw new IllegalArgumentException("artifact hash mismatch: " + relative); String content = new String(bytes, StandardCharsets.UTF_8); long count = content.lines().filter(line -> !line.isEmpty()).count(); if (count != (long) jsNumber(artifact.get("rows"))) throw new IllegalArgumentException("artifact row count mismatch: " + relative); } }

    public static ObjectNode rebuildIndex(Path root) { return Registry.rebuild(root); }
    public static ObjectNode rebuildIndex(String root) { return rebuildIndex(Path.of(root)); }
    public static ObjectNode validateRegistry(Path root) { return Registry.validate(root); }
    public static ObjectNode validateRegistry(String root) { return validateRegistry(Path.of(root)); }
    public static ObjectNode compactLegacy(Path path, String asset) { return compactLegacy(path, asset, "EXPOSED_CONFIRMATION"); }
    public static ObjectNode compactLegacy(Path path, String asset, String evidencePhase) { return compactLegacyValue(path, asset.toLowerCase(Locale.ROOT), evidencePhase); }

    private static ObjectNode compactLegacyValue(Path path, String asset, String phase) { byte[] bytes = PathConfinement.readSinglyLinkedFile(path.toAbsolutePath().normalize(), "legacy source"); JsonNode source; try { source = MAPPER.readTree(bytes); } catch (Exception error) { throw new IllegalArgumentException("legacy source cannot be parsed: " + path, error); } ArrayNode recovered = assetMetrics(source, asset), trades = assetTrades(source, asset); Map<String, ObjectNode> candidates = new LinkedHashMap<>(); for (JsonNode row : recovered) if (bool(row.get("candidate_id")) && !candidates.containsKey(text(row.get("candidate_id")))) { JsonNode definition = present(row.get("candidate_definition")) ? row.get("candidate_definition") : JSON.objectNode().put("id", text(row.get("candidate_id"))).put("legacy_unrecovered", true); candidates.put(text(row.get("candidate_id")), JSON.objectNode().put("candidate_id", text(row.get("candidate_id"))).put("behavior_sha256", hash(definition)).set("definition", cloneNode(definition))); } ArrayNode metrics = JSON.arrayNode(); for (JsonNode row : recovered) { ObjectNode copy = objectCopy(row, "metric"); copy.remove("candidate_definition"); metrics.add(copy); } List<String> omissions = new ArrayList<>(); if (trades.isEmpty()) omissions.add("NO_RECOVERABLE_COMPACT_TRADES"); if (!source.has("feature_contract")) omissions.add("NO_EXPLICIT_FEATURE_CONTRACT"); if (!source.has("evidence_phase")) omissions.add("EVIDENCE_PHASE_INFERRED"); ObjectNode out = JSON.objectNode().put("source_path", path.toString()).put("source_sha256", LegacyResearchSupport.hash(bytes)).put("asset", asset).put("evidence_phase", phase); out.set("source_schema", present(source.get("schema")) ? cloneNode(source.get("schema")) : NullNode.instance); out.set("source_generated_at", present(source.get("generated_at")) ? cloneNode(source.get("generated_at")) : NullNode.instance); out.set("candidates", arrayOf(candidates.values())); out.set("metrics", metrics); out.set("trades", trades); out.set("explicit_omissions", strings(omissions)); return out; }

    private static LegacySource source(String path, String first, String second, String phase) { return new LegacySource(path, List.of(first, second), phase); }
    private static boolean present(JsonNode value) { return value != null && !value.isNull() && !value.isMissingNode(); }
    private static String optionText(JsonNode value, String key, String fallback) { return value != null && value.has(key) && present(value.get(key)) ? text(value.get(key)) : fallback; }
    private static boolean containsText(JsonNode values, String expected) { for (JsonNode value : rows(values)) if (expected.equals(text(value))) return true; return false; }
    private static void metric(ObjectNode out, String name, JsonNode metrics, String... keys) { for (String key : keys) if (metrics != null && metrics.has(key) && metrics.get(key).isNumber() && Double.isFinite(metrics.get(key).doubleValue())) { out.set(name, cloneNode(metrics.get(key))); return; } out.putNull(name); }
    private static ObjectNode statusFor(JsonNode metrics, String phase, boolean pitSafe, JsonNode acceptance) { List<String> reasons = new ArrayList<>(); if (!pitSafe) reasons.add("POINT_IN_TIME_NOT_VERIFIED"); if (!(jsNumber(metrics == null ? null : metrics.get("completed_trades")) > 0)) reasons.add("NO_COMPLETED_TRADES"); if (!(jsNumber(metrics == null ? null : metrics.get("search_adjusted_expectancy_r")) > 0)) reasons.add("MISSING_OR_NONPOSITIVE_SEARCH_ADJUSTED_EXPECTANCY"); if (acceptance != null && acceptance.path("minimums").isObject()) acceptance.path("minimums").fields().forEachRemaining(entry -> { if (entry.getValue().isNumber() && !(jsNumber(metrics == null ? null : metrics.get(entry.getKey())) >= entry.getValue().doubleValue())) reasons.add("BELOW_" + entry.getKey().toUpperCase(Locale.ROOT)); }); ObjectNode out = JSON.objectNode(); if (!reasons.isEmpty()) out.put("status", "REJECTED").set("reasons", strings(reasons)); else if ("PROSPECTIVE_LIVE".equals(phase)) out.put("status", "CANDIDATE_REVIEW").set("reasons", strings(List.of("SEPARATE_ACTIVATION_REVIEW_REQUIRED"))); else out.put("status", "SHADOW").set("reasons", strings(List.of("RESEARCH_EVIDENCE_ONLY"))); return out; }
    private static boolean pitSafe(JsonNode definition, String asset) { for (JsonNode series : rows(definition.path("feature_contract").get("series"))) if (asset.equals(lower(series.get("asset"))) && !"VERIFIED".equals(text(series.path("point_in_time").get("status")))) return false; return true; }
    private static ObjectNode artifact(String path, ArrayNode rows) { byte[] bytes = jsonlBytes(rows); return JSON.objectNode().put("path", path).put("sha256", LegacyResearchSupport.hash(bytes)).put("rows", rows.size()); }
    private static void createRealDirectories(Path approved, Path target) { try { if (!Files.exists(approved, LinkOption.NOFOLLOW_LINKS)) Files.createDirectories(approved); PathConfinement.requireRealDirectory(approved, "approved root"); Path current = approved; for (Path component : approved.relativize(target)) { current = current.resolve(component); if (!Files.exists(current, LinkOption.NOFOLLOW_LINKS)) Files.createDirectory(current); PathConfinement.requireRealDirectory(current, "output directory"); } } catch (Exception error) { throw error instanceof RuntimeException runtime ? runtime : new IllegalArgumentException("output directory cannot be created", error); } }

    private static ArrayNode assetMetrics(JsonNode source, String asset) { ArrayNode result = JSON.arrayNode(); for (JsonNode report : rows(source.get("reports"))) { JsonNode assetReport = report.path("assets").get(asset); if (present(assetReport)) addMetric(result, first(report, "candidate", "definition"), present(assetReport.get("metrics")) ? assetReport.get("metrics") : assetReport, asset, "ASSET", null, report.path("primary_accepted").asBoolean(false)); else if (asset.equals(lower(report.get("asset"))) || !bool(report.get("asset"))) addMetric(result, first(report, "candidate", "definition"), first(report, "metrics", "report.metrics"), asset, bool(report.get("asset")) ? "ASSET" : "PORTFOLIO", report.get("series"), false); } for (JsonNode item : rows(source.get("results"))) { JsonNode metric = item.path("per_asset").get(asset); if (!present(metric)) metric = item.path("assets").get(asset); if (!present(metric) && asset.equals(lower(item.get("asset")))) metric = item.get("metrics"); if (present(metric)) addMetric(result, present(item.get("candidate")) ? item.get("candidate") : item, present(metric.get("metrics")) ? metric.get("metrics") : metric, asset, "ASSET", null, false); } for (JsonNode series : rows(source.get("series"))) if (lower(series.get("series")).startsWith(asset + "|")) { for (JsonNode item : rows(series.get("leaderboard"))) addMetric(result, item.get("candidate"), item.get("metrics"), asset, "ASSET", series.get("series"), false); addMetric(result, series.path("validation").get("selected"), series.path("validation").path("walk_forward_oos").get("metrics"), asset, "ASSET", series.get("series"), true); addMetric(result, series.path("validation").path("holdout").get("selected"), series.path("validation").path("holdout").path("report").get("metrics"), asset, "ASSET", series.get("series"), true); } if (present(source.get("metrics")) && (!bool(source.get("asset")) || asset.equals(lower(source.get("asset"))))) { JsonNode candidate = first(source, "candidate", "definition"); if (!present(candidate)) candidate = JSON.objectNode().put("id", optionText(source, "strategy_id", "legacy-" + asset)); addMetric(result, candidate, source.get("metrics"), asset, "ASSET", null, true); } return result; }
    private static void addMetric(ArrayNode result, JsonNode candidate, JsonNode metrics, String asset, String scope, JsonNode series, boolean selected) { if (metrics == null || !metrics.isObject()) return; String id = candidate != null && candidate.isTextual() ? text(candidate) : optionText(candidate, "id", optionText(candidate, "candidate_id", null)); ObjectNode row = JSON.objectNode().put("scope", scope); if (series == null) row.putNull("series_id"); else row.set("series_id", cloneNode(series)); if ("ASSET".equals(scope)) row.put("asset", asset); else row.putNull("asset"); if (id == null) row.putNull("candidate_id"); else row.put("candidate_id", id); row.set("candidate_definition", candidate != null && candidate.isObject() ? cloneNode(candidate) : NullNode.instance); row.put("selected", selected); row.set("metrics", compactMetrics(metrics)); result.add(row); }
    private static ArrayNode assetTrades(JsonNode source, String asset) { ArrayNode result = JSON.arrayNode(); addTrades(result, source.get("trades"), asset); for (JsonNode report : rows(source.get("reports"))) { addTrades(result, report.get("trades"), asset); addTrades(result, report.path("assets").path(asset).get("trades"), asset); } for (JsonNode series : rows(source.get("series"))) if (lower(series.get("series")).startsWith(asset + "|")) { addTrades(result, series.path("validation").path("walk_forward_oos").get("trades"), asset); addTrades(result, series.path("validation").path("holdout").path("report").get("trades"), asset); } return result; }
    private static void addTrades(ArrayNode result, JsonNode trades, String asset) { for (JsonNode raw : rows(trades)) if (!bool(raw.get("asset")) || asset.equals(lower(raw.get("asset")))) { ObjectNode trade = objectCopy(raw, "trade"); trade.put("asset", asset); result.add(trade); } }

    private static final class Registry {
        private Registry() {}

        static ObjectNode rebuild(Path rootInput) { Path root = rootInput.toAbsolutePath().normalize(); createRealDirectories(root, root); ArrayNode definitions = JSON.arrayNode(), experiments = JSON.arrayNode(), runs = JSON.arrayNode(), performance = JSON.arrayNode(); for (Path path : jsonFiles(root.resolve("definitions"))) { JsonNode value = readJSON(path); ObjectNode row = pick(value, "strategy_id", "version", "created_at", "status", "stage", "hypothesis_family", "precommit", "parent_evidence"); row.put("path", slash(root.relativize(path))); definitions.add(row); } sortByPath(definitions); for (Path path : namedFiles(root.resolve("experiments"), "experiment.json")) { JsonNode value = readJSON(path); ObjectNode row = pick(value, "experiment_id", "created_at", "evidence_phase", "required_assets", "stage", "hypothesis_family", "evidence_family_ids", "ablation_role", "parent_evidence"); row.put("path", slash(root.relativize(path))); experiments.add(row); } sortByPath(experiments);
            Map<String, JsonNode> decisions = new LinkedHashMap<>(), evidenceByRun = new LinkedHashMap<>(); for (Path path : namedFiles(root.resolve("runs"), "run.json")) { JsonNode value = readJSON(path); String schema = text(value.get("schema")); if (RUN_SCHEMA.equals(schema)) validateRunDirectoryValue(path.getParent(), value); else if (RUN_V2_SCHEMA.equals(schema)) LegacyResearchV2.validateV2Document(value); else if (LegacyResearchV3.RUN_V3_SCHEMA.equals(schema)) LegacyResearchV3.validateRunV3(value); else throw new IllegalArgumentException("unsupported run schema " + schema); decisions.put(text(value.get("run_id")), value.path("decisions")); ObjectNode row = JSON.objectNode().put("path", slash(root.relativize(path))).put("run_id", text(value.get("run_id"))).put("evidence_phase", text(value.get("evidence_phase"))); if (RUN_SCHEMA.equals(schema)) { row.set("generated_at", cloneNode(value.get("generated_at"))); row.put("experiment_id", text(value.path("experiment").get("experiment_id"))).put("portfolio_status", text(value.path("decisions").path("portfolio").get("status"))); row.set("assets", assetList(value.path("decisions").get("per_asset"))); ObjectNode counts = JSON.objectNode(); value.path("artifacts").fields().forEachRemaining(entry -> counts.put(entry.getKey(), entry.getValue().path("rows").asInt())); row.set("counts", counts); } else { row.set("schema", cloneNode(value.get("schema"))); row.set("generated_at", present(value.get("generated_at")) ? cloneNode(value.get("generated_at")) : NullNode.instance); row.put("experiment_id", optionText(value, "experiment_id", null)).put("portfolio_status", text(value.path("decisions").path("portfolio").get("status"))); row.set("assets", assetList(value.path("decisions").get("per_asset"))); JsonNode evidence = null; if (LegacyResearchV3.RUN_V3_SCHEMA.equals(schema) && bool(value.get("evidence_bundle_sha256"))) { Path evidencePath = root.resolve("evidence-bundles").resolve(text(value.get("evidence_bundle_sha256")) + ".json"); if (!Files.exists(evidencePath, LinkOption.NOFOLLOW_LINKS)) throw new IllegalArgumentException("v3 run evidence bundle is missing"); evidence = readJSON(evidencePath); LegacyResearchV3.validateEvidenceBundleV2(evidence); evidenceByRun.put(text(value.get("run_id")), evidence); } JsonNode metrics = evidence != null ? evidence.get("metrics") : value.get("metrics"), trades = evidence != null ? evidence.get("trades") : value.get("trades"); row.set("counts", JSON.objectNode().put("metrics", rows(metrics).size()).put("trades", rows(trades).size())); } runs.add(row); } sortByPath(runs);
            for (JsonNode run : runs) { String id = text(run.get("run_id")); JsonNode metrics; if (RUN_SCHEMA.equals(text(readJSON(root.resolve(text(run.get("path")))).get("schema")))) metrics = readJSONL(root.resolve(text(run.get("path"))).getParent().resolve("metrics.jsonl")); else { JsonNode source = evidenceByRun.get(id); if (source == null) source = readJSON(root.resolve(text(run.get("path")))); metrics = source.get("metrics"); } for (JsonNode metric : rows(metrics)) { ObjectNode values = metric.path("metrics").isObject() ? objectCopy(metric.get("metrics"), "metrics") : objectCopy(metric, "metric"); values.remove(List.of("run_id", "experiment_id", "evidence_phase", "asset", "scope", "candidate_id", "status")); ObjectNode row = JSON.objectNode().put("run_id", id); putNullable(row, "experiment_id", nullable(text(run.get("experiment_id"))) == null ? null : JSON.textNode(text(run.get("experiment_id")))); row.put("evidence_phase", text(run.get("evidence_phase"))).put("scope", optionText(metric, "scope", bool(metric.get("asset")) ? "ASSET" : "PORTFOLIO")); putNullable(row, "asset", metric.get("asset")); putNullable(row, "candidate_id", metric.get("candidate_id")); JsonNode decision = bool(metric.get("asset")) ? rows(decisions.get(id).get("per_asset")).stream().filter(item -> text(item.get("asset")).equals(text(metric.get("asset")))).findFirst().orElse(null) : decisions.get(id).get("portfolio"); putNullable(row, "status", decision == null ? null : decision.get("status")); row.setAll(values); performance.add(row); } } performance = canonicalRows(rows(performance)); String generatedAt = latest(definitions, experiments, runs); ObjectNode index = JSON.objectNode().put("schema", REGISTRY_SCHEMA); putNullable(index, "generated_at", generatedAt == null ? null : JSON.textNode(generatedAt)); index.set("definitions", definitions); index.set("experiments", experiments); index.set("runs", runs); index.set("performance", performance); publish(root, "index.json", compact(index)); publish(root, "INDEX.md", markdownIndex(index).getBytes(StandardCharsets.UTF_8)); publish(root, "PERFORMANCE.md", markdownPerformance(index).getBytes(StandardCharsets.UTF_8)); return index; }

        static ObjectNode validate(Path rootInput) { Path root = rootInput.toAbsolutePath().normalize(); List<String> errors = new ArrayList<>(); try { for (Path path : LegacyResearchSupport.walk(root)) { try { if (Files.size(path) > MAX_TRACKED_ARTIFACT_BYTES) errors.add(slash(root.relativize(path)) + " exceeds 10MiB"); } catch (Exception error) { errors.add(slash(root.relativize(path)) + ": " + error.getMessage()); } } } catch (RuntimeException error) { errors.add(error.getMessage()); }
            for (Path path : jsonFiles(root.resolve("definitions"))) try { JsonNode value = readJSON(path); validateDefinition(value); String expected = "definitions/" + text(value.get("strategy_id")) + "/" + text(value.get("version")) + ".json"; if (!expected.equals(slash(root.relativize(path)))) throw new IllegalArgumentException("definition path/version mismatch"); } catch (RuntimeException error) { errors.add(slash(root.relativize(path)) + ": " + error.getMessage()); }
            for (Path path : namedFiles(root.resolve("experiments"), "experiment.json")) try { JsonNode value = readJSON(path), candidateSet = readJSON(path.getParent().resolve("candidates.json")), definition = readJSON(root.resolve(text(value.path("definition").get("path")))); if (EXPERIMENT_V2_SCHEMA.equals(text(value.get("schema")))) { LegacyResearchV2.validateExperimentV2(value, definition); LegacyResearchV2.validateCandidateSetV2(candidateSet, value); } else { validateExperiment(value); validateCandidateSet(candidateSet); } if (!hash(definition).equals(text(value.path("definition").get("sha256")))) throw new IllegalArgumentException("definition cross-file hash mismatch"); if (!hash(candidateSet).equals(text(value.path("candidate_set").get("sha256"))) || !"candidates.json".equals(text(value.path("candidate_set").get("path")))) throw new IllegalArgumentException("candidate-set cross-file hash mismatch"); } catch (RuntimeException error) { errors.add(slash(root.relativize(path)) + ": " + error.getMessage()); }
            for (Path path : namedFiles(root.resolve("runs"), "run.json")) try { JsonNode value = readJSON(path); if (RUN_V2_SCHEMA.equals(text(value.get("schema")))) LegacyResearchV2.validateV2Document(value); else if (LegacyResearchV3.RUN_V3_SCHEMA.equals(text(value.get("schema")))) LegacyResearchV3.validateRunV3(value); else validateRunDirectory(path.getParent()); } catch (RuntimeException error) { errors.add(slash(root.relativize(path)) + ": " + error.getMessage()); }
            for (Path path : jsonFiles(root.resolve("definitions"))) try {
                JsonNode value = readJSON(path);
                if (LegacyResearchV2.DEFINITION_V2_SCHEMA.equals(text(value.get("schema")))) {
                    validateV2DefinitionBinding(root, value);
                }
            } catch (RuntimeException error) {
                errors.add(slash(root.relativize(path)) + ": " + error.getMessage());
            }
            for (Path path : namedFiles(root.resolve("runs"), "run.json")) try {
                JsonNode value = readJSON(path);
                if (LegacyResearchV2.RUN_V2_SCHEMA.equals(text(value.get("schema")))) {
                    validateV2RunBindings(root, path, value);
                } else if (LegacyResearchV3.RUN_V3_SCHEMA.equals(text(value.get("schema")))) {
                    validateV3RunBindings(root, path, value);
                }
            } catch (RuntimeException error) {
                errors.add(slash(root.relativize(path)) + ": " + error.getMessage());
            }
            ResearchSchemaRegistry schemas = ResearchSchemaRegistry.defaultRegistry();
            for (Path path : jsonFiles(root)) try {
                JsonNode value = readJSON(path);
                schemas.validateContractSchema(value);
                if (LegacyResearchV2.DATA_MANIFEST_SCHEMA.equals(text(value.get("schema")))) {
                    LegacyResearchV2.validateDataManifest(value);
                }
                if (LegacyResearchV2.EVIDENCE_BUNDLE_SCHEMA.equals(text(value.get("schema")))) {
                    LegacyResearchV2.validateEvidenceBundle(value);
                }
                if (LegacyResearchV3.EVIDENCE_BUNDLE_V2_SCHEMA.equals(text(value.get("schema")))) {
                    LegacyResearchV3.validateEvidenceBundleV2(value);
                }
                if (LegacyResearchV3.RUN_V3_SCHEMA.equals(text(value.get("schema")))) {
                    LegacyResearchV3.validateRunV3(value);
                }
            } catch (RuntimeException error) {
                errors.add(slash(root.relativize(path)) + ": " + error.getMessage());
            }
            if (errors.isEmpty() && Files.exists(root.resolve("index.json"), LinkOption.NOFOLLOW_LINKS)) { String before = new String(PathConfinement.readSinglyLinkedFile(root.resolve("index.json"), "index"), StandardCharsets.UTF_8); rebuild(root); String after = new String(PathConfinement.readSinglyLinkedFile(root.resolve("index.json"), "index"), StandardCharsets.UTF_8); if (!before.equals(after)) errors.add("index.json was stale"); } if (!errors.isEmpty()) throw new IllegalArgumentException(String.join("\n", errors)); return JSON.objectNode().put("valid", true); }

        private static void validateV2DefinitionBinding(Path root, JsonNode definition) {
            JsonNode reference = definition.get("precommit");
            String relative = optionText(reference, "path",
                    "precommits/" + text(reference == null ? null
                            : reference.get("precommit_id")) + ".json");
            JsonNode precommit = readJSON(root.resolve(relative));
            if (!LegacyResearchV2.PRECOMMIT_SCHEMA.equals(text(precommit.get("schema")))
                    || !LegacyResearchV2.hash(precommit)
                    .equals(text(reference == null ? null : reference.get("sha256")))) {
                throw new IllegalArgumentException("definition precommit cross-file hash mismatch");
            }
        }

        private static void validateV2RunBindings(Path root, Path path, JsonNode run) {
            LegacyResearchV2.validateV2Document(run);
            if (!path.getParent().getFileName().toString().equals(text(run.get("run_id")))) {
                throw new IllegalArgumentException("v2 run directory name does not match run_id");
            }
            Path experimentDirectory = root.resolve("experiments")
                    .resolve(text(run.get("experiment_id")));
            JsonNode experiment = readJSON(experimentDirectory.resolve("experiment.json"));
            JsonNode definition = readJSON(root.resolve(
                    text(experiment.path("definition").get("path"))));
            JsonNode candidateSet = readJSON(experimentDirectory.resolve(
                    text(experiment.path("candidate_set").get("path"))));
            JsonNode precommit = readJSON(root.resolve(
                    text(definition.path("precommit").get("path"))));
            if (!LegacyResearchV2.hash(precommit).equals(text(run.get("precommit_sha256")))
                    || !LegacyResearchV2.hash(definition)
                    .equals(text(run.get("definition_sha256")))
                    || !LegacyResearchV2.hash(experiment)
                    .equals(text(run.get("experiment_sha256")))
                    || !LegacyResearchV2.hash(candidateSet)
                    .equals(text(run.get("candidate_set_sha256")))) {
                throw new IllegalArgumentException("v2 run cross-file hash mismatch");
            }
            if ("AUTHORITATIVE_RECOMPUTED".equals(text(run.get("provenance")))) {
                String evidenceHash = text(run.get("evidence_bundle_sha256"));
                Path evidencePath = root.resolve("evidence-bundles")
                        .resolve(evidenceHash + ".json");
                if (!Files.exists(evidencePath, LinkOption.NOFOLLOW_LINKS)) {
                    throw new IllegalArgumentException(
                            "authoritative run evidence bundle is missing");
                }
                JsonNode evidence = readJSON(evidencePath);
                ObjectNode context = JSON.objectNode();
                context.set("experiment", cloneNode(experiment));
                context.set("candidateSet", cloneNode(candidateSet));
                LegacyResearchV2.validateEvidenceBundle(evidence, context);
                String fileName = evidencePath.getFileName().toString();
                if (!fileName.equals(text(evidence.get("content_sha256")) + ".json")
                        || !evidenceHash.equals(text(evidence.get("content_sha256")))) {
                    throw new IllegalArgumentException(
                            "authoritative run evidence bundle hash/path mismatch");
                }
            }
            if (!text(run.get("stage")).equals(text(experiment.get("stage")))
                    || !text(run.get("evidence_phase"))
                    .equals(text(experiment.get("evidence_phase")))
                    || !text(run.get("strategy_id")).equals(text(definition.get("strategy_id")))
                    || !LegacyResearchV2.stable(run.get("required_assets"))
                    .equals(LegacyResearchV2.stable(experiment.get("required_assets")))) {
                throw new IllegalArgumentException(
                        "v2 run duplicated metadata does not match bound definition/experiment");
            }
        }

        private static void validateV3RunBindings(Path root, Path path, JsonNode run) {
            LegacyResearchV3.validateRunV3(run);
            if (!path.getParent().getFileName().toString().equals(text(run.get("run_id")))) {
                throw new IllegalArgumentException("v3 run directory name does not match run_id");
            }
            if (!bool(run.get("evidence_bundle_sha256"))) return;
            Path evidencePath = root.resolve("evidence-bundles")
                    .resolve(text(run.get("evidence_bundle_sha256")) + ".json");
            if (!Files.exists(evidencePath, LinkOption.NOFOLLOW_LINKS)) {
                throw new IllegalArgumentException("v3 run evidence bundle is missing");
            }
            JsonNode evidence = readJSON(evidencePath);
            LegacyResearchV3.validateEvidenceBundleV2(evidence);
            if (!text(evidence.get("content_sha256"))
                    .equals(text(run.get("evidence_bundle_sha256")))
                    || !text(evidence.get("experiment_sha256"))
                    .equals(text(run.get("experiment_sha256")))
                    || !text(evidence.get("evidence_phase"))
                    .equals(text(run.get("evidence_phase")))
                    || !LegacyResearchV3.hash(evidence.get("decisions"))
                    .equals(LegacyResearchV3.hash(run.get("decisions")))) {
                throw new IllegalArgumentException("v3 run/evidence decision or hash mismatch");
            }
        }

        private static List<Path> jsonFiles(Path root) { if (!Files.exists(root, LinkOption.NOFOLLOW_LINKS)) return List.of(); return LegacyResearchSupport.walk(root).stream().filter(path -> path.getFileName().toString().endsWith(".json")).toList(); }
        private static List<Path> namedFiles(Path root, String name) { if (!Files.exists(root, LinkOption.NOFOLLOW_LINKS)) return List.of(); return LegacyResearchSupport.walk(root).stream().filter(path -> path.getFileName().toString().equals(name)).toList(); }
        private static void sortByPath(ArrayNode array) { List<JsonNode> values = new ArrayList<>(rows(array)); values.sort(Comparator.comparing(row -> text(row.get("path")))); array.removeAll(); values.forEach(array::add); }
        private static ArrayNode assetList(JsonNode decisions) { ArrayNode result = JSON.arrayNode(); for (JsonNode row : rows(decisions)) result.add(text(row.get("asset"))); return result; }
        private static String latest(ArrayNode... sources) { List<String> values = new ArrayList<>(); for (ArrayNode source : sources) for (JsonNode row : source) if (bool(row.get("created_at"))) values.add(text(row.get("created_at"))); else if (bool(row.get("generated_at"))) values.add(text(row.get("generated_at"))); values.sort(String::compareTo); return values.isEmpty() ? null : values.get(values.size() - 1); }
        private static void publish(Path root, String name, byte[] bytes) { SecureFileOperations.atomicReplace(root, name, bytes); }
        private static byte[] compact(JsonNode value) { try { return (MAPPER.writeValueAsString(value) + "\n").getBytes(StandardCharsets.UTF_8); } catch (Exception error) { throw new IllegalArgumentException(error); } }
        private static String markdownIndex(JsonNode index) { List<String> lines = new ArrayList<>(List.of("# Strategy research index", "", "Generated: " + optionText(index, "generated_at", "deterministic/no timestamp"), "", "Definitions: " + index.path("definitions").size() + " · Experiments: " + index.path("experiments").size() + " · Runs: " + index.path("runs").size() + " · Metric rows: " + index.path("performance").size(), "", "| Run | Phase | Experiment | Portfolio | Assets | Metrics | Trades |", "|---|---|---|---|---|---:|---:|")); for (JsonNode row : rows(index.get("runs"))) lines.add("| " + text(row.get("run_id")).substring(0, Math.min(12, text(row.get("run_id")).length())) + " | " + text(row.get("evidence_phase")) + " | " + text(row.get("experiment_id")) + " | " + text(row.get("portfolio_status")) + " | " + join(row.get("assets")) + " | " + row.path("counts").path("metrics").asInt() + " | " + row.path("counts").path("trades").asInt() + " |"); return String.join("\n", lines) + "\n"; }
        private static String markdownPerformance(JsonNode index) { List<String> lines = new ArrayList<>(List.of("# Historical strategy performance", "", "| Strategy candidate | Asset | Phase | Status | Trades | Expectancy R | PF | Max DD % | Run |", "|---|---|---|---|---:|---:|---:|---:|---|")); for (JsonNode row : rows(index.get("performance"))) lines.add("| " + optionText(row, "candidate_id", "portfolio") + " | " + optionText(row, "asset", "portfolio") + " | " + text(row.get("evidence_phase")) + " | " + optionText(row, "status", "SHADOW") + " | " + text(row.get("completed_trades")) + " | " + text(row.get("expectancy_r")) + " | " + text(row.get("profit_factor")) + " | " + text(row.get("max_drawdown_pct")) + " | " + text(row.get("run_id")).substring(0, Math.min(12, text(row.get("run_id")).length())) + " |"); return String.join("\n", lines) + "\n"; }
        private static String join(JsonNode values) { List<String> result = new ArrayList<>(); for (JsonNode value : rows(values)) result.add(text(value)); return String.join(", ", result); }
    }

    private static String slash(Path path) { return path.toString().replace('\\', '/'); }
    private static String nullable(String value) { return value == null || value.isEmpty() ? null : value; }
    private static void putNullable(ObjectNode target, String field, JsonNode value) { if (value == null || value.isNull() || value.isMissingNode()) target.putNull(field); else target.set(field, cloneNode(value)); }
}
