package com.tradinganalytics.research.legacy;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.NullNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.tradinganalytics.infrastructure.security.PathConfinement;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static com.tradinganalytics.research.legacy.LegacyResearchSupport.*;

/** Honest read-only inventory port of {@code migrate-research-v3.mjs}. */
public final class LegacyResearchMigrationV3 {
    private LegacyResearchMigrationV3() {}

    public static ObjectNode migrate(Path root, Path output) {
        Path sourceRoot = root.toAbsolutePath().normalize(), runsRoot = sourceRoot.resolve("runs"), target = output.toAbsolutePath().normalize(); ArrayNode files = JSON.arrayNode(); Map<String, ArrayNode> index = new LinkedHashMap<>(); LegacyResearchV3.CORE_UNIVERSE.forEach(asset -> index.put(asset, JSON.arrayNode()));
        if (Files.exists(runsRoot, LinkOption.NOFOLLOW_LINKS)) { PathConfinement.requireRealDirectory(runsRoot, "migration runs root"); List<Path> directories; try (var stream = Files.list(runsRoot)) { directories = stream.sorted(Comparator.comparing(path -> path.getFileName().toString())).toList(); } catch (Exception error) { throw new IllegalArgumentException("migration runs cannot be listed", error); }
            for (Path runDirectory : directories) { BasicFileAttributes attributes; try { attributes = Files.readAttributes(runDirectory, BasicFileAttributes.class, LinkOption.NOFOLLOW_LINKS); } catch (Exception error) { throw new IllegalArgumentException("migration run entry cannot be inspected: " + runDirectory.getFileName(), error); } if (attributes.isSymbolicLink() || !attributes.isDirectory()) throw new IllegalArgumentException("migration run entry must be a real directory: " + runDirectory.getFileName()); String runId = runDirectory.getFileName().toString(); Path runPath = runDirectory.resolve("run.json"); if (!Files.exists(runPath, LinkOption.NOFOLLOW_LINKS)) continue; byte[] runBytes = PathConfinement.readSinglyLinkedFile(runPath, "migration run"); JsonNode run = parse(runBytes, runPath); ObjectNode record = JSON.objectNode().put("run_id", runId).put("path", "runs/" + runId + "/run.json").put("sha256", nodeBufferHash(runBytes)); putNullable(record, "schema", run.get("schema")); JsonNode phase = firstTruthy(run, "evidence_phase"); if (phase == null) phase = run.path("experiment").get("evidence_phase"); putNullable(record, "phase", phase); putNullable(record, "status", run.path("decisions").path("portfolio").get("status")); ObjectNode hashes = JSON.objectNode(); if (run.path("artifacts").isObject()) run.path("artifacts").fields().forEachRemaining(entry -> putNullable(hashes, entry.getKey(), entry.getValue().get("sha256"))); record.set("artifact_hashes", hashes); files.add(record);
                JsonNode metricsPathNode = run.path("artifacts").path("metrics").get("path"); if (!bool(metricsPathNode)) continue; String relative = PathConfinement.repositoryRelativePath(text(metricsPathNode), "migration metrics path"); Path metricsPath = runDirectory.resolve(relative).normalize(); if (!metricsPath.startsWith(runDirectory) || !Files.exists(metricsPath, LinkOption.NOFOLLOW_LINKS)) continue; String metrics = new String(PathConfinement.readSinglyLinkedFile(metricsPath, "migration metrics"), StandardCharsets.UTF_8); for (String line : metrics.split("\\r?\\n")) { if (line.isEmpty()) continue; JsonNode metric; try { metric = MAPPER.readTree(line); } catch (Exception ignored) { continue; } String asset = lower(metric.get("asset")); if (!index.containsKey(asset)) continue; JsonNode payload = metric.path("metrics").isObject() ? metric.get("metrics") : metric; JsonNode decision = rows(run.path("decisions").get("per_asset")).stream().filter(row -> asset.equals(lower(row.get("asset")))).findFirst().orElse(JSON.objectNode()); JsonNode omissions = firstTruthy(metric, "omissions"); if (omissions == null) omissions = firstTruthy(payload, "omissions"); if (omissions == null) omissions = firstTruthy(decision, "omissions"); if (omissions == null) omissions = run.get("omissions"); if (omissions == null) omissions = JSON.arrayNode(); ObjectNode row = JSON.objectNode(); JsonNode strategyId = firstTruthy(metric, "strategy_id"); if (strategyId == null) strategyId = firstTruthy(run, "strategy_id"); if (strategyId == null) strategyId = run.path("experiment").get("strategy_id"); putNullable(row, "strategy_id", strategyId); JsonNode candidateId = firstTruthy(metric, "candidate_id", "candidate"); if (candidateId == null) candidateId = payload.get("candidate_id"); putNullable(row, "candidate_id", candidateId); row.put("run_id", runId).put("metric_sha256", LegacyResearchV2.hash(metric)).put("original_row_sha256", LegacyResearchV2.hash(metric)); JsonNode metricPhase = firstTruthy(metric, "phase", "evidence_phase"); if (metricPhase == null) metricPhase = firstTruthy(payload, "phase", "evidence_phase"); if (metricPhase == null) metricPhase = phase; putNullable(row, "phase", metricPhase); JsonNode status = firstTruthy(metric, "status"); if (status == null) status = firstTruthy(payload, "status"); if (status == null) status = decision.get("status"); if (status == null) status = run.path("decisions").path("portfolio").get("status"); putNullable(row, "status", status); row.set("omissions", cloneNode(omissions)); JsonNode count = payload.has("completed_trades") ? payload.get("completed_trades") : payload.get("trade_count"); row.put("completed_trades", (int) jsNumber(count)); double expectancy = jsNumber(payload.get("expectancy_r")); if (payload.has("expectancy_r") && Double.isFinite(expectancy)) row.put("expectancy_r", expectancy); else row.putNull("expectancy_r"); row.put("provenance", "LEGACY_READ_ONLY"); index.get(asset).add(row); }
            }
        }
        for (String asset : LegacyResearchV3.CORE_UNIVERSE) { List<JsonNode> sorted = new ArrayList<>(rows(index.get(asset))); sorted.sort(Comparator.comparing(row -> text(row.get("strategy_id")) + "|" + text(row.get("candidate_id")) + "|" + text(row.get("run_id")))); index.put(asset, arrayOf(sorted)); }
        ArrayNode omissions = JSON.arrayNode(); int missingAssets = 0; for (String asset : LegacyResearchV3.CORE_UNIVERSE) if (index.get(asset).isEmpty()) { ObjectNode omission = JSON.objectNode().put("asset", asset); omission.set("missing", strings(List.of("durable_metrics_or_trades", "PIT_manifest", "authoritative_v3_evidence"))); omissions.add(omission); missingAssets++; } omissions.add(JSON.objectNode().put("missing", "legacy raw data is not rewritten as PIT-safe")); omissions.add(JSON.objectNode().put("missing", "legacy narrated metrics are not authoritative v3 metrics")); omissions.add(JSON.objectNode().put("missing", "SEALED_CONFIRMATION and ACTIVE are never minted by migration"));
        ObjectNode report = JSON.objectNode().put("schema", "strategy-research-v3-migration/1").put("source_root", sourceRoot.toString()); report.set("source_schemas_preserved", strings(List.of("strategy-definition/1", "strategy-experiment/1", "strategy-run/1", "strategy-definition/2", "strategy-experiment/2", "strategy-run/2"))); report.set("reference_assets", strings(LegacyResearchV3.CORE_UNIVERSE)); report.set("excluded_assets", strings(List.of("doge"))); report.set("runs", files); ObjectNode deterministic = JSON.objectNode(); index.forEach(deterministic::set); report.set("deterministic_index", deterministic); report.put("promotion_policy", "legacy artifacts remain EXTERNAL_EXPOSED/read-only; absent PIT/source/trade detail is recorded as an omission, never reconstructed"); report.set("omissions", omissions); ObjectNode identity = pick(report, "schema", "source_schemas_preserved", "reference_assets", "excluded_assets", "runs", "deterministic_index", "promotion_policy", "omissions"); report.put("content_sha256", LegacyResearchV2.hash(identity)); writeExclusive(target, jsonBytes(report)); ObjectNode result = JSON.objectNode().put("path", target.toString()).put("runs", files.size()).put("omissions", missingAssets); result.set("assets", strings(LegacyResearchV3.CORE_UNIVERSE)); return result;
    }

    private static JsonNode parse(byte[] bytes, Path path) { try { return MAPPER.readTree(bytes); } catch (Exception error) { throw new IllegalArgumentException("migration run cannot be parsed: " + path, error); } }
    private static String nodeBufferHash(byte[] bytes) { ObjectNode buffer = JSON.objectNode().put("type", "Buffer"); ArrayNode data = buffer.putArray("data"); for (byte value : bytes) data.add(Byte.toUnsignedInt(value)); return LegacyResearchSupport.hash(buffer); }
    private static void putNullable(ObjectNode target, String key, JsonNode value) { if (value == null || value.isNull() || value.isMissingNode()) target.putNull(key); else target.set(key, cloneNode(value)); }
    private static JsonNode firstTruthy(JsonNode value, String... keys) { if (value == null) return null; for (String key : keys) if (bool(value.get(key))) return value.get(key); return null; }
}
