package com.tradinganalytics.research.legacy;

import static com.tradinganalytics.research.legacy.LegacyResearchSupport.JSON;
import static com.tradinganalytics.research.legacy.LegacyResearchSupport.cloneNode;
import static com.tradinganalytics.research.legacy.LegacyResearchSupport.jsNumber;
import static com.tradinganalytics.research.legacy.LegacyResearchSupport.rows;
import static com.tradinganalytics.research.legacy.LegacyResearchSupport.text;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.NullNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/** Stack composition, structural evidence validation, and implementation-readiness evidence. */
final class LegacyResearchNextArtifacts {
    /** Frozen oracle identity; this is contract metadata, not a runtime dependency. */
    private static final String LEGACY_NODE_MAJOR = "22";
    private static final Set<String> AUTHORITATIVE_SCHEMAS = Set.of(
            LegacyResearchNext.STACK_SCHEMA, LegacyResearchNext.SOURCE_RECEIPT_SCHEMA,
            "strategy-source-registry/1", LegacyResearchNext.EXPOSURE_SCHEMA,
            LegacyResearchNext.EXECUTION_SCHEMA, LegacyResearchNext.PORTFOLIO_SCHEMA,
            LegacyResearchNext.PROSPECTIVE_SCHEMA, LegacyResearchNext.ACTIVATION_SCHEMA,
            LegacyResearchNext.REVOCATION_SCHEMA, LegacyResearchNext.READINESS_SCHEMA,
            LegacyResearchNext.RUN_SCHEMA, LegacyResearchNext.EVIDENCE_SCHEMA,
            "strategy-candidate-set/4", "strategy-execution-result/1",
            "strategy-portfolio-result/1", "strategy-wfo-result/1", "strategy-stress-result/1",
            "strategy-prospective-attestation/1", "strategy-prospective-gate/1",
            "prospective-monitoring/2", "strategy-research-index/4", "strategy-data-manifest/2",
            "research-feature-set/1", "research-label-set/1", "strategy-acceptance-contract/1");
    private LegacyResearchNextArtifacts() {}

    static ObjectNode makeStackContract(JsonNode options) {
        JsonNode precommit = options == null ? null : options.get("precommit"), candidates = LegacyResearchNext.first(options, "candidateSet", "candidate_set");
        LegacyResearchNext.validateNextPrecommit(precommit); LegacyResearchNext.validateCandidateSetNext(candidates, precommit);
        JsonNode execution = options == null ? null : options.get("execution"); if (execution == null || execution.isNull()) execution = LegacyResearchNext.makeExecutionPolicy();
        JsonNode portfolio = LegacyResearchNext.first(options, "portfolioPolicy", "portfolio_policy"); if (portfolio == null || portfolio.isNull()) portfolio = LegacyResearchNext.makePortfolioPolicy();
        LegacyResearchNext.validateExecutionPolicy(execution); LegacyResearchNext.validatePortfolioPolicy(portfolio);
        String manifest = sha(LegacyResearchNext.first(options, "manifestSha256", "manifest_sha256"), "manifestSha256"), feature = sha(LegacyResearchNext.first(options, "featureSetSha256", "feature_set_sha256"), "featureSetSha256"), labels = sha(LegacyResearchNext.first(options, "labelSetSha256", "label_set_sha256"), "labelSetSha256");
        String phase = LegacyResearchNext.optionText(options, "evidencePhase", "evidence_phase", "DEVELOPMENT"); if (!List.of("DEVELOPMENT", "WALK_FORWARD_OOS", "EXPOSED_CONFIRMATION", "CI_ATTESTED_CONFIRMATION", "PROSPECTIVE_LIVE").contains(phase)) throw new IllegalArgumentException("local stack cannot mint a sealed evidence phase");
        String id = LegacyResearchNext.optionText(options, "stackId", "stack_id", "stack-" + text(precommit.get("content_sha256")).substring(0, 12));
        JsonNode definition = options == null ? null : options.get("definition"), acceptance = options == null ? null : options.get("acceptance"), executor = options == null ? null : options.get("executor"), environment = options == null ? null : options.get("environment");
        ObjectNode definitionValue = definition == null ? JSON.objectNode().put("precommit_sha256", text(precommit.get("content_sha256"))).put("candidate_set_sha256", text(candidates.get("content_sha256"))) : null;
        JsonNode acceptanceValue = acceptance != null ? acceptance : precommit.path("experiment").has("acceptance") ? precommit.path("experiment").get("acceptance") : JSON.objectNode().put("phase", phase);
        JsonNode executorValue = executor != null ? executor : JSON.objectNode().put("execution_policy_sha256", text(execution.get("content_sha256"))).put("module", "strategy-research-next/4");
        JsonNode environmentValue = environment != null ? environment : JSON.objectNode()
                .put("runtime", "node")
                .put("major", LEGACY_NODE_MAJOR)
                .put("contract", "strategy-research-next/4");
        String definitionSha = definition != null && LegacyResearchNext.present(definition.get("content_sha256")) ? text(definition.get("content_sha256")) : LegacyResearchNext.hash(definitionValue);
        String acceptanceSha = acceptance != null && LegacyResearchNext.present(acceptance.get("content_sha256")) ? text(acceptance.get("content_sha256")) : LegacyResearchNext.hash(acceptanceValue);
        String executorSha = executor != null && LegacyResearchNext.present(executor.get("content_sha256")) ? text(executor.get("content_sha256")) : LegacyResearchNext.hash(executorValue);
        String environmentSha = environment != null && LegacyResearchNext.present(environment.get("content_sha256")) ? text(environment.get("content_sha256")) : LegacyResearchNext.hash(environmentValue);
        ObjectNode genesisOptions = JSON.objectNode().put("hypothesisFamily", id).put("datasetRootSha256", manifest); genesisOptions.set("candidates", JSON.arrayNode()); ObjectNode genesis = LegacyResearchNext.appendExposureLedger(genesisOptions); String exposure = LegacyResearchNext.optionText(options, "exposureLedgerSha256", "exposure_ledger_sha256", text(genesis.get("content_sha256")));
        ObjectNode lineage = JSON.objectNode().put("definition_sha256", definitionSha).put("acceptance_sha256", acceptanceSha).put("executor_sha256", executorSha).put("environment_sha256", environmentSha).put("exposure_ledger_sha256", exposure);
        ObjectNode universe = JSON.objectNode(); universe.set("tradable_assets", LegacyResearchNext.strings(LegacyResearchNext.UNIVERSE)); universe.set("excluded_assets", LegacyResearchNext.strings(List.of("doge"))); universe.put("venue", "binance"); universe.set("instrument_scope", LegacyResearchNext.strings(LegacyResearchNext.EXECUTABLE_INSTRUMENTS));
        JsonNode generation = options == null ? null : options.get("generation"); if (generation == null || generation.isNull()) { ObjectNode generated = JSON.objectNode().put("method", "GRID").put("declared_k", candidates.path("declared_k").asInt()).put("effective_k", candidates.path("effective_k").asInt()).put("seed", 1); generated.set("provenance", cloneNode(candidates.path("generator").get("provenance"))); generation = generated; }
        ObjectNode pit = JSON.objectNode().put("source_registry_assigned_only", true).put("completed_bar_only", true).put("strict_as_of_join", true).put("revised_inputs_fail_closed", true); ObjectNode data = JSON.objectNode().put("manifest_sha256", manifest).put("feature_set_sha256", feature).put("label_set_sha256", labels); data.set("pit_policy", pit); data.set("coverage", JSON.objectNode());
        ObjectNode selection = JSON.objectNode().put("method", "STATIONARY_BLOCK_CANDIDATE_SET_MAX_STAT").put("family_k_cumulative", true), resampling = JSON.objectNode().put("synchronized_market_episodes", true).put("block_bootstrap", true), plateau = JSON.objectNode().put("required", true).put("isolated_optimum_rejected", true).put("executable", true); plateau.set("result", NullNode.instance); ObjectNode ablations = JSON.objectNode().put("required", true); ablations.set("topology", LegacyResearchNext.strings(List.of("CORE_PREMISE", "ADD_ONE_CONTEXT", "LEAVE_ONE_OUT", "SCORE_FREE_BASELINE", "SIMPLEST_FALSIFIER"))); ablations.set("results", NullNode.instance); ObjectNode statistics = JSON.objectNode(); statistics.set("selection", selection); statistics.set("resampling", resampling); statistics.set("plateau", plateau); statistics.set("ablations", ablations);
        ObjectNode activation = JSON.objectNode().put("authorized", false).put("status", "RESEARCH_ONLY"); ObjectNode contract = JSON.objectNode().put("schema", LegacyResearchNext.STACK_SCHEMA).put("stack_id", id).put("precommit_sha256", text(precommit.get("content_sha256"))).put("definition_sha256", definitionSha).put("candidate_set_sha256", text(candidates.get("content_sha256"))).put("acceptance_sha256", acceptanceSha).put("executor_sha256", executorSha).put("environment_sha256", environmentSha).put("exposure_ledger_sha256", exposure); contract.set("lineage", lineage); contract.set("universe", universe); contract.set("generation", cloneNode(generation)); contract.set("data", data); contract.set("execution", cloneNode(execution)); contract.set("statistics", statistics); contract.set("portfolio_policy", cloneNode(portfolio)); contract.put("evidence_phase", phase).put("decision", "SHADOW"); contract.set("activation", activation); contract = LegacyResearchNext.withHash(contract); LegacyResearchNext.validateSchema(contract); return contract;
    }

    static ObjectNode readinessAudit(JsonNode options) {
        ObjectNode returns = JSON.objectNode(); returns.set("probe_a", JSON.objectNode().put("episode_1", 1).put("episode_2", -1)); returns.set("probe_b", JSON.objectNode().put("episode_1", 0).put("episode_2", 0)); ObjectNode probeOptions = JSON.objectNode().put("iterations", 8).put("seed", 19); ObjectNode probe = LegacyResearchNext.stationaryBlockMaxStatistic(returns, probeOptions);
        boolean statistics = probe.path("synchronized_draws").asBoolean(false) && probe.path("finite_sample_correction").asBoolean(false) && !probe.path("spa").asBoolean(true); boolean execution = false, portfolio = false; try { execution = LegacyResearchNext.validateExecutionPolicy(LegacyResearchNext.makeExecutionPolicy()); } catch (RuntimeException ignored) {} try { portfolio = LegacyResearchNext.validatePortfolioPolicy(LegacyResearchNext.makePortfolioPolicy()); } catch (RuntimeException ignored) {}
        ObjectNode checks = JSON.objectNode().put("governance", true).put("statistics", statistics).put("execution", execution).put("portfolio", portfolio).put("pit", LegacyResearchNext.sourceIsPublic("binance:spot-ohlcv")).put("prospective", false).put("runner_attestation", false).put("prospective_gates", false).put("external_trust_root", trustRootConfigured()).put("revocation_registry", false).put("activation", false); boolean prospectiveReady = false, activationReady = false;
        ArrayNode dimensions = JSON.arrayNode(); dimensions.add(dimension("governance_reproducibility", 9.5, 9.5, null, List.of("immutable precommit", "content hashes", "append-only exposure ledger"))); dimensions.add(dimension("statistical_selection", 9, statistics ? 9 : 6, "implementation-contract coverage only; no empirical strategy performance or production readiness is implied", List.of("deterministic stationary max-stat probe", "nested purge/embargo WFO contract", "plateau and ablation contracts"))); dimensions.add(dimension("pit_data_readiness", 8, checks.path("pit").asBoolean() ? 8 : 5, "public historical data cannot reproduce every private revision/vintage", List.of("hashed source registry", "feature/label separation", "availability-time receipts"))); dimensions.add(dimension("execution_realism", 7, execution ? 7 : 5, "implementation-contract coverage only; public bars cannot reproduce historical order-book queues/private fills", List.of("validated execution-policy probe", "all next 1m children", "adverse collision/capacity/outage contract"))); dimensions.add(dimension("portfolio_risk_realism", 9, portfolio ? 9 : 6, null, List.of("mandatory risk policy", "event-time MTM", "ES/loss runs/MRC/ruin"))); dimensions.add(dimension("prospective_validation", 9, prospectiveReady ? 9 : 4, prospectiveReady ? null : "future-only GitHub/OIDC runner and attestation are not configured", List.of("future-only reservation", "hash-chained outcomes", "fast gate and drift controls"))); dimensions.add(dimension("activation_infrastructure", 9, activationReady ? 9 : 3, activationReady ? null : "external trust root, revocation registry, and attestation are not configured", List.of("Ed25519 lease", "asset + portfolio approvals", "expiry/revocation/drift demotion")));
        ObjectNode machine = checks.deepCopy(); machine.put("prospective_runner_available", checks.path("runner_attestation").asBoolean(false)).put("external_attestation_available", checks.path("prospective_gates").asBoolean(false)).put("external_trust_root_configured", checks.path("external_trust_root").asBoolean(false)); ObjectNode activation = JSON.objectNode().put("ready", activationReady).put("active_requires_signature", true).put("full_risk_after_approval", true).put("probation_ramp", false); ArrayNode limitations = LegacyResearchNext.strings(List.of("Scores are machine-checked implementation-contract coverage, not empirical strategy performance or production readiness.", "No strategy is ACTIVE from research output.", "Historical PIT authority remains source-dependent.", "Execution is public-bar based and not a queue simulator.", "GitHub/OIDC artifact custody and independent external attestation root are deployment prerequisites.", "Prospective and activation scores remain below target until those artifacts are machine-verified.")); String generated = LegacyResearchNext.optionText(options, "generatedAt", "generated_at", LegacyResearchNext.DETERMINISTIC_READINESS_TIME); ObjectNode audit = JSON.objectNode().put("schema", LegacyResearchNext.READINESS_SCHEMA).put("generated_at", generated).put("readiness_basis", "IMPLEMENTATION_CONTRACT_COVERAGE_NOT_EMPIRICAL_PERFORMANCE"); audit.set("machine_checks", machine); audit.set("dimensions", dimensions); audit.set("activation_infrastructure", activation); audit.put("active_strategy_count", 0); audit.set("limitations", limitations); audit = LegacyResearchNext.withHash(audit); LegacyResearchNext.validateSchema(audit); return audit;
    }

    static String readinessMarkdown(JsonNode audit) { if (audit == null || !LegacyResearchNext.READINESS_SCHEMA.equals(text(audit.get("schema"))) || !LegacyResearchNext.ownHash(audit).equals(text(audit.get("content_sha256")))) throw new IllegalArgumentException("readiness audit hash/schema is invalid"); List<String> lines = new ArrayList<>(List.of("# Strategy-research/4 readiness audit", "", "Generated: " + text(audit.get("generated_at")), "Basis: " + text(audit.get("readiness_basis")), "", "| Dimension | Score | Target | Status |", "|---|---:|---:|---|")); for (JsonNode row : rows(audit.get("dimensions"))) lines.add("| " + text(row.get("id")) + " | " + jsNumberText(row.get("score")) + " | " + jsNumberText(row.get("target")) + " | " + (jsNumber(row.get("score")) >= jsNumber(row.get("target")) ? "READY" : "LIMITED") + " |"); lines.addAll(List.of("", "Activation infrastructure: " + (audit.path("activation_infrastructure").path("ready").asBoolean(false) ? "READY" : "BLOCKED"), "Actual ACTIVE strategies: " + text(audit.get("active_strategy_count")), "", "Limitations:")); for (JsonNode item : rows(audit.get("limitations"))) lines.add("- " + text(item)); lines.add(""); return String.join("\n", lines); }

    static boolean validateWfoStructure(JsonNode value, JsonNode options) {
        requireEvidenceArtifact(value, "strategy-wfo-result/1", "WFO result"); if (!value.path("folds").isArray() || value.path("folds").isEmpty()) throw new IllegalArgumentException("WFO requires non-empty folds"); if (!value.path("cumulative_runtime_k").canConvertToInt() || value.path("cumulative_runtime_k").asInt() < 1) throw new IllegalArgumentException("WFO cumulative runtime K must be positive"); if (!value.path("candidate_accounting").isObject() || !value.path("candidate_accounting").path("all_evaluated_behaviors_included").asBoolean(false) || !value.path("candidate_accounting").path("cumulative_k").canConvertToInt() || value.path("candidate_accounting").path("cumulative_k").asInt() < 1) throw new IllegalArgumentException("WFO candidate accounting is incomplete"); String exposure = text(LegacyResearchNext.first(options, "exposureLedgerSha256", "exposure_ledger_sha256")); if (!text(value.get("exposure_ledger_sha256")).equals(exposure) || !text(value.path("candidate_accounting").get("exposure_ledger_sha256")).equals(exposure)) throw new IllegalArgumentException("WFO exposure ledger lineage mismatch"); JsonNode lineage = value.path("lineage"); Map<String, String> expected = Map.of("stack_sha256", text(LegacyResearchNext.first(options, "stackSha256", "stack_sha256")), "precommit_sha256", text(LegacyResearchNext.first(options, "precommitSha256", "precommit_sha256")), "candidate_sha256", text(LegacyResearchNext.first(options, "candidateSha256", "candidate_sha256")), "data_manifest_sha256", text(LegacyResearchNext.first(options, "manifestSha256", "manifest_sha256")), "exposure_ledger_sha256", exposure); for (Map.Entry<String, String> entry : expected.entrySet()) if (!LegacyResearchNext.isSha(lineage.get(entry.getKey())) || !text(lineage.get(entry.getKey())).equals(entry.getValue())) throw new IllegalArgumentException("WFO " + entry.getKey() + " lineage mismatch or missing"); if (!"TRAIN_ONLY".equals(text(value.get("selection_phase"))) || !LegacyResearchNext.present(value.get("test_phase"))) throw new IllegalArgumentException("WFO phase separation is missing"); for (String key : List.of("plateau", "ablations", "execution", "stress", "portfolio")) if (!value.path(key).path("pass").isBoolean()) throw new IllegalArgumentException("WFO " + key + " structural outcome is missing"); if (!value.path("gate_pass").isBoolean() || !List.of("REJECTED", "CANDIDATE_REVIEW").contains(text(value.get("decision"))) || value.path("gate_pass").asBoolean() != "CANDIDATE_REVIEW".equals(text(value.get("decision")))) throw new IllegalArgumentException("WFO gate/decision invariant is invalid"); return true;
    }

    static boolean validateAuthoritativeWfoArtifact(JsonNode value, JsonNode options) { validateWfoStructure(value, options); double max = LegacyResearchNext.optionDouble(options, "maxPValue", "max_p_value", .2); JsonNode statistic = value.get("statistic"); if (statistic == null || "NOT_RUN".equals(text(statistic.get("status"))) || statistic.path("spa").asBoolean(true) || !statistic.path("selection_gate").asBoolean(false) || !Double.isFinite(jsNumber(statistic.get("p_value"))) || jsNumber(statistic.get("p_value")) > max) throw new IllegalArgumentException("authoritative WFO statistic did not run or pass threshold"); for (String key : List.of("plateau", "ablations", "execution", "stress", "portfolio")) if (!value.path(key).path("pass").asBoolean(false)) throw new IllegalArgumentException("authoritative WFO " + key + " gate is missing or failed"); if (!value.path("portfolio").path("marks_bound").asBoolean(false) || !value.path("portfolio").path("funding_attribution_only").asBoolean(false) || !value.path("gate_pass").asBoolean(false) || !"CANDIDATE_REVIEW".equals(text(value.get("decision")))) throw new IllegalArgumentException("authoritative WFO selection/execution/stress/portfolio gates are not all passing"); return true; }

    static boolean validateStressStructure(JsonNode value, JsonNode options) { requireEvidenceArtifact(value, "strategy-stress-result/1", "stress result"); if (!value.path("scenarios").isArray() || value.path("scenarios").isEmpty() || !value.path("pass").isBoolean()) throw new IllegalArgumentException("stress result structural outcome is missing"); JsonNode lineage = value.path("lineage"); Map<String, JsonNode> expected = new LinkedHashMap<>(); expected.put("stack_sha256", LegacyResearchNext.first(options, "stackSha256", "stack_sha256")); expected.put("candidate_sha256", LegacyResearchNext.first(options, "candidateSha256", "candidate_sha256")); expected.put("data_manifest_sha256", LegacyResearchNext.first(options, "manifestSha256", "manifest_sha256")); expected.put("exposure_ledger_sha256", LegacyResearchNext.first(options, "exposureLedgerSha256", "exposure_ledger_sha256")); for (Map.Entry<String, JsonNode> entry : expected.entrySet()) if (!LegacyResearchNext.isSha(lineage.get(entry.getKey())) || LegacyResearchNext.present(entry.getValue()) && !text(lineage.get(entry.getKey())).equals(text(entry.getValue()))) throw new IllegalArgumentException("stress " + entry.getKey() + " lineage mismatch or missing"); return true; }

    static boolean validateNextArtifact(JsonNode value, JsonNode options) {
        String schema = value == null ? "" : text(value.get("schema"));
        if (!AUTHORITATIVE_SCHEMAS.contains(schema)) throw new IllegalArgumentException("unsupported authoritative v4 schema " + (schema.isEmpty() ? "?" : schema));
        if (!LegacyResearchNext.present(value.get("content_sha256")) || !text(value.get("content_sha256")).equals(LegacyResearchNext.ownHash(value))) throw new IllegalArgumentException("authoritative " + schema + " retained hash is invalid");
        LegacyResearchNext.validateSchema(value);
        switch (schema) {
            case LegacyResearchNext.SOURCE_RECEIPT_SCHEMA -> LegacyResearchNext.validateSourceReceipt(value);
            case "strategy-source-registry/1" -> { if (!value.path("sources").isArray() || rows(value.get("sources")).stream().anyMatch(row -> !LegacyResearchNext.present(row.get("source_id")) || !LegacyResearchNext.PIT_TIERS.contains(text(row.get("maximum_pit_tier"))))) throw new IllegalArgumentException("source registry is not a hashed complete authority"); }
            case "strategy-data-manifest/2" -> { /* retained hash and schema above are the record contract */ }
            case "research-feature-set/1" -> { if (!value.path("labels_allowed").isBoolean() || value.path("labels_allowed").asBoolean()) throw new IllegalArgumentException("feature set is not a frozen label-free artifact"); requireSha(value.get("data_manifest_sha256"), "feature_set.data_manifest_sha256"); validatePartitions(value, "feature set has no bound physical partitions"); }
            case "research-label-set/1" -> { if (!value.path("predictor_eligible").isBoolean() || value.path("predictor_eligible").asBoolean()) throw new IllegalArgumentException("label set is not a frozen non-predictor artifact"); requireSha(value.get("data_manifest_sha256"), "label_set.data_manifest_sha256"); validatePartitions(value, "label set has no bound physical partitions"); }
            case "strategy-acceptance-contract/1" -> { /* retained hash above */ }
            case LegacyResearchNext.EXPOSURE_SCHEMA -> LegacyResearchNext.validateExposureLedger(value);
            case LegacyResearchNext.EXECUTION_SCHEMA -> LegacyResearchNext.validateExecutionPolicy(value);
            case LegacyResearchNext.PORTFOLIO_SCHEMA -> LegacyResearchNext.validatePortfolioPolicy(value);
            case LegacyResearchNext.STACK_SCHEMA -> { for (String key : List.of("definition_sha256", "candidate_set_sha256", "acceptance_sha256", "executor_sha256", "environment_sha256", "exposure_ledger_sha256")) requireSha(value.get(key), "stack." + key); for (String key : List.of("definition_sha256", "acceptance_sha256", "executor_sha256", "environment_sha256", "exposure_ledger_sha256")) if (!text(value.path("lineage").get(key)).equals(text(value.get(key)))) throw new IllegalArgumentException("stack lineage " + key + " mismatch"); }
            case "strategy-candidate-set/4" -> LegacyResearchNext.validateCandidateSetNext(value);
            case "strategy-execution-result/1" -> { if (!value.path("pass").asBoolean(false) || !"RESEARCH_ONLY".equals(text(value.get("activation"))) || !value.path("fee_schedule_bound").asBoolean(false)) throw new IllegalArgumentException("execution result is not a verified passing research artifact"); }
            case "strategy-portfolio-result/1" -> { if (!value.path("pass").asBoolean(false) || !"RESEARCH_ONLY".equals(text(value.get("activation"))) || !value.path("marks_bound").asBoolean(false) || !value.path("funding_attribution_only").asBoolean(false)) throw new IllegalArgumentException("portfolio result is not a verified passing marked research artifact"); }
            case "strategy-wfo-result/1" -> validateWfoStructure(value, lineageOptions(value));
            case "strategy-stress-result/1" -> validateStressStructure(value, lineageOptions(value));
            case "strategy-prospective-attestation/1" -> { if (!"PASS".equals(text(value.get("status"))) || !value.path("pass").asBoolean(false) || !LegacyResearchNext.isSha(value.get("ledger_head_sha256")) || !LegacyResearchNext.isSha(value.get("lineage_sha256"))) throw new IllegalArgumentException("prospective attestation is not a verified passing artifact"); }
            case "strategy-prospective-gate/1" -> { if (!value.path("pass").asBoolean(false) || !List.of("statistical", "stress").contains(text(value.get("gate"))) || !LegacyResearchNext.isSha(value.get("ledger_head_sha256")) || !LegacyResearchNext.isSha(value.get("lineage_sha256"))) throw new IllegalArgumentException("prospective gate is not a verified passing artifact"); }
            case "strategy-research-index/4" -> { if (!value.path("records").isArray() || rows(value.get("records")).stream().anyMatch(row -> !LegacyResearchNext.present(row.get("schema")) || !LegacyResearchNext.isSha(row.get("content_sha256")) || !LegacyResearchNext.present(row.get("path")))) throw new IllegalArgumentException("research index contains an unbound record"); }
            case LegacyResearchNext.PROSPECTIVE_SCHEMA -> LegacyResearchNext.validateProspectiveLedger(value);
            case LegacyResearchNext.ACTIVATION_SCHEMA -> { JsonNode publicKey = LegacyResearchNext.first(options, "publicKeyPem", "public_key_pem"); JsonNode keyId = LegacyResearchNext.first(options, "trustRootKeyId", "trust_root_key_id"); if (!LegacyResearchNext.present(publicKey) || !LegacyResearchNext.present(keyId)) throw new IllegalArgumentException("activation record validation requires an external trust-root public key and configured key ID"); ObjectNode verification = LegacyResearchNext.verifyActivationArtifact(value, options); if (!verification.path("valid").asBoolean(false)) throw new IllegalArgumentException("activation evidence/signature is not valid: " + LegacyResearchNext.optionText(verification, "reason", "status", "")); }
            case LegacyResearchNext.REVOCATION_SCHEMA -> { /* schema and retained hash above */ }
            case LegacyResearchNext.READINESS_SCHEMA -> { ObjectNode actual = readinessAudit(JSON.objectNode().put("generatedAt", text(value.get("generated_at")))); if (!value.get("dimensions").equals(actual.get("dimensions")) || value.path("active_strategy_count").asInt() != 0 || value.path("activation_infrastructure").path("ready").asBoolean() != actual.path("activation_infrastructure").path("ready").asBoolean()) throw new IllegalArgumentException("readiness audit is not derived from current machine checks"); }
            case LegacyResearchNext.RUN_SCHEMA -> { for (String key : List.of("stack_sha256", "precommit_sha256", "candidate_sha256", "manifest_sha256", "feature_set_sha256", "label_set_sha256", "executor_sha256", "acceptance_sha256", "environment_sha256", "exposure_ledger_sha256")) requireSha(value.path("lineage").get(key), "run.lineage." + key); if (!value.path("candidate_accounting").path("all_candidates_recorded").asBoolean(false)) throw new IllegalArgumentException("authoritative run must record every candidate outcome"); for (String key : List.of("execution", "wfo", "stress", "portfolio", "statistic")) if (!value.has(key)) throw new IllegalArgumentException("authoritative run must include execution/WFO/statistic/stress/portfolio stage records"); }
            case LegacyResearchNext.EVIDENCE_SCHEMA -> { requireSha(value.get("run_sha256"), "evidence.run_sha256"); for (String key : List.of("stack_sha256", "precommit_sha256", "candidate_sha256", "manifest_sha256", "feature_set_sha256", "label_set_sha256", "executor_sha256", "acceptance_sha256", "environment_sha256", "exposure_ledger_sha256")) requireSha(value.path("lineage").get(key), "evidence.lineage." + key); for (String key : List.of("execution", "wfo", "statistic", "stress", "portfolio")) if (!value.has(key)) throw new IllegalArgumentException("evidence must include every authoritative stage"); }
            default -> { /* exhaustive set */ }
        }
        return true;
    }

    static JsonNode requireEvidenceArtifact(JsonNode value, String schema, String name) { if (value == null || !schema.equals(text(value.get("schema"))) || !text(value.get("content_sha256")).equals(LegacyResearchNext.ownHash(value))) throw new IllegalArgumentException(name + " is missing, schema-invalid, or retained-hash tampered"); LegacyResearchNext.validateSchema(value); return value; }
    private static void requireSha(JsonNode value, String name) { if (!LegacyResearchNext.isSha(value)) throw new IllegalArgumentException(name + " must be a SHA-256 hash"); }
    private static void validatePartitions(JsonNode value, String message) { if (!value.path("partitions").isArray() || value.path("partitions").isEmpty() || rows(value.get("partitions")).stream().anyMatch(row -> !LegacyResearchNext.present(row.get("path")) || !LegacyResearchNext.isSha(row.get("sha256")) || !row.path("row_count").canConvertToInt())) throw new IllegalArgumentException(message); }
    private static ObjectNode lineageOptions(JsonNode value) { ObjectNode options = JSON.objectNode(); JsonNode lineage = value.path("lineage"); options.set("stackSha256", cloneNode(lineage.get("stack_sha256"))); options.set("precommitSha256", cloneNode(lineage.get("precommit_sha256"))); options.set("candidateSha256", cloneNode(lineage.get("candidate_sha256"))); options.set("manifestSha256", cloneNode(lineage.get("data_manifest_sha256"))); options.set("exposureLedgerSha256", cloneNode(lineage.get("exposure_ledger_sha256"))); return options; }
    private static String sha(JsonNode value, String name) { if (!LegacyResearchNext.isSha(value)) throw new IllegalArgumentException(name + " must be a SHA-256 hash"); return text(value); }
    private static ObjectNode dimension(String id, double target, double score, String cap, List<String> evidence) { ObjectNode row = JSON.objectNode().put("id", id).put("target", target).put("score", score); if (cap != null) row.put("cap_reason", cap); row.set("evidence", LegacyResearchNext.strings(evidence)); return row; }
    private static boolean trustRootConfigured() { return LegacyResearchNext.present(JSON.textNode(System.getenv("STRATEGY_RESEARCH_TRUST_ROOT_KEY_ID"))) && LegacyResearchNext.present(JSON.textNode(System.getenv("STRATEGY_RESEARCH_TRUST_ROOT_PUBLIC_KEY_PEM"))); }
    private static String jsNumberText(JsonNode value) { double number = jsNumber(value); return number == Math.rint(number) ? Long.toString((long) number) : Double.toString(number); }
}
