#!/usr/bin/env sh
set -eu

# Emits the immutable build marker consumed by the launcher and packaged CLI.
# The marker intentionally excludes target/ and the marker itself, and never
# contains the final JAR digest (which would be self-referential).

ROOT=${1:-}
if [ -z "$ROOT" ]; then
  ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
fi
ROOT=$(CDPATH= cd -- "$ROOT" && pwd)

hash_file() {
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | awk '{print $1}'
  else
    sha256sum "$1" | awk '{print $1}'
  fi
}

hash_stdin() {
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 | awk '{print $1}'
  else
    sha256sum | awk '{print $1}'
  fi
}

# Capture the actual runtime used by Maven.  JAVA_HOME is intentionally not
# used as the identity: the compiler/runtime vendor and version are what can
# change generated bytecode and resource processing.
JAVA_VERSION_OUTPUT=$(LC_ALL=C java -version 2>&1 || true)
JAVA_SETTINGS_OUTPUT=$(LC_ALL=C java -XshowSettings:properties -version 2>&1 || true)
JAVA_VERSION=$(printf '%s\n' "$JAVA_VERSION_OUTPUT" | sed -n '1p' | tr -d '\r')
JAVA_VENDOR=$(printf '%s\n' "$JAVA_SETTINGS_OUTPUT" | sed -n 's/^ *java.vendor = //p' | head -n 1 | tr -d '\r')
JAVA_RUNTIME=$(printf '%s\n' "$JAVA_SETTINGS_OUTPUT" | sed -n 's/^ *java.runtime.name = //p' | head -n 1 | tr -d '\r')
[ -n "$JAVA_VERSION" ] || JAVA_VERSION=unknown
[ -n "$JAVA_VENDOR" ] || JAVA_VENDOR=unknown
[ -n "$JAVA_RUNTIME" ] || JAVA_RUNTIME=unknown
TOOLCHAIN_FINGERPRINT=$(
  printf 'java.version=%s\njava.vendor=%s\njava.runtime.name=%s\n' \
    "$JAVA_VERSION" "$JAVA_VENDOR" "$JAVA_RUNTIME" | hash_stdin
)

file_list() {
  (
    cd "$ROOT"
    find analytics-* -type f \( \
      -path '*/src/main/*' -o -path '*/src/test/*' -o \
      -name 'pom.xml' \) -print
    find schemas -type f -print 2>/dev/null || true
    find tools -maxdepth 1 -type f -print 2>/dev/null || true
    find .mvn -type f -print 2>/dev/null || true
    printf '%s\n' mvnw mvnw.cmd pom.xml tools/build-input-identity.sh
  ) | LC_ALL=C sort -u
}

# Hash the path and bytes together. This avoids collisions between files that
# happen to have the same contents at different paths and is stable across
# checkouts with different absolute roots.
INPUT_FINGERPRINT=$(
  {
    while IFS= read -r relative; do
      if [ -f "$ROOT/$relative" ]; then
        printf '%s  %s\n' "$(hash_file "$ROOT/$relative")" "$relative"
      fi
    done <<EOF
$(file_list)
EOF
    printf '%s  %s\n' "$TOOLCHAIN_FINGERPRINT" '__toolchain/java-runtime'
  } | LC_ALL=C sort | hash_stdin
)

revision=UNKNOWN
dirty=false
if command -v git >/dev/null 2>&1 && git -C "$ROOT" rev-parse --verify HEAD >/dev/null 2>&1; then
  revision=$(git -C "$ROOT" rev-parse HEAD)
  # Only source/build inputs affect this flag. Reports and ignored research
  # caches do not make an executable claim that its compiled source is dirty.
  # Use fixed quoted pathspecs rather than expanding file_list as shell
  # arguments; source paths may contain spaces and staged changes must count.
  if ! git -C "$ROOT" diff --quiet HEAD -- \
      'analytics-*/src/main/**' 'analytics-*/src/test/**' 'analytics-*/pom.xml' \
      'schemas/**' 'tools/**' '.mvn/**' 'mvnw' 'mvnw.cmd' 'pom.xml'; then
    dirty=true
  fi
  if git -C "$ROOT" ls-files --others --exclude-standard -- \
      'analytics-*/src/main/**' 'analytics-*/src/test/**' 'analytics-*/pom.xml' \
      'schemas/**' 'tools/**' '.mvn/**' 'mvnw' 'mvnw.cmd' 'pom.xml' | grep -q .; then
    dirty=true
  fi
fi

if [ "${BUILD_INPUT_IDENTITY_FINGERPRINT_ONLY:-false}" = true ]; then
  printf '%s\n' "$INPUT_FINGERPRINT"
  exit 0
fi

printf '%s\n' \
  '# Generated at package time. Do not edit or commit.' \
  'schema=analytics-build-identity/1' \
  'build.input_fingerprint='"$INPUT_FINGERPRINT" \
  'build.revision='"$revision" \
  'build.dirty_source='"$dirty" \
  'build.java_version='"$JAVA_VERSION" \
  'build.java_vendor='"$JAVA_VENDOR" \
  'build.java_runtime='"$JAVA_RUNTIME" \
  'build.toolchain_fingerprint='"$TOOLCHAIN_FINGERPRINT" \
  'build.maven_wrapper_sha256='"$(hash_file "$ROOT/mvnw" 2>/dev/null || printf unknown)" \
  'build.root_pom_sha256='"$(hash_file "$ROOT/pom.xml")"
